### ISSUE TITLE
Managing the frequency of creating compiled template files.

### ISSUE THREAD

**Issue by tchalvak** [bobthecow/mustache.php#118]
So when templates are being compiled, they create files like...

__Mustache_4779899c3aa97955a22babf831412bcf.php  __Mustache_a13c9c8b33fb6a28f7e20312e98c4fb9.php  __Mustache_fede53e567ef0897692b01f9bdd68d7c.php
__Mustache_479dd872ea7777c20af5a6bc7e6c0518.php  __Mustache_a231f26a8cb202a24f0f0a45ef0e0f10.php  __Mustache_fee38ad449a30dfad2a1e98b08f35a3a.php
__Mustache_47db93914ab56850b1a8bed31d92c02d.php  __Mustache_a27d0a890ccbb040f9c9cc4a08e24eb3.php  __Mustache_ff4be422e1796adadcc215d265518311.php

I assume these are hashes of content.  It's all greek to me, unfortunately I seem to have some runaway compiling of templates going on, and I have no idea where to start to debug the issue.
kzqai@hal3k:~/src/sherman/core/templates$ ls compiled/ | wc -l
666
kzqai@hal3k:~/src/sherman/core/templates$ ls ./ | wc -l
63

So 666 compiled templates coming from 63 original files.  Is that bad?  Should I try to mitigate at this point?  Where do I start to determine where excess is happening?

**Comment by acicali** [comment]
Sorry if I'm hijacking this, it seemed like a good place to post. I've just discovered 268GB of Mustache.php cache files... is there some condition that could cause 100% cache miss? (just a guess)

I'm using version 2.5.1 (admittedly quite old), but it's only one particular website that has this issue, many others using the same version do not. Any quick pointers of where to begin troubleshooting this issue?

Thanks for your time.

**Comment by bobthecow** [comment]
Wow. That’s pretty impressive. 

Do the cached template files predate your upgrade to >= 2.5.0? Prior to that, all lambda section templates were cached the same way as regular templates, which would usually result in a really high miss percentage. 

Do you have lambda section caching enabled? If you do, and you use lambda sections whose return values vary significantly, you’ll get a high number of cache misses. 

Do you use a string loader with a dynamic value in the template string? An example might be interpolating a time stamp or a price or something into the template string before rendering, rather than as a variable rendered into the template?

**Comment by acicali** [comment]
Thanks for your help. Hmm... I hope I can answer these:

1. This particular project has only ever used v2.5.1, so no.
2. The only option being set is the cache dir... new Mustache_Engine(array('cache' => '/path/to/cache')); So I don't think so.
3. This is probably the problem... it's quite harry. This site has about 100 domains pointed at it, and there are various parts of the template that are different per domain.

Would it be best to just disable caching for this particular site? Seems like the path of least resistance.

**Comment by bobthecow** [comment]
You could do that, but it might be a significant performance hit.

You might be able to track down the offending templates by clearing out the cache directory, then letting it run for a bit, then sorting the cached templates by date created. After the cache is warm, any new template files created have a really high likelihood of being your problem, and you should be able to figure out what they are by viewing the source.
