### ISSUE TITLE
Partials loading as variables and not filename?

### ISSUE THREAD

**Issue by feketegy** [bobthecow/mustache.php#135]
Is there a way to load partials based on an array of filename values?

Currently if I write this `{{> sidebar}}` it will look for views/sidebar.mustache. (based on the template loader class where I can specify where to look for the templates)

Ideally I want that `{{> sidebar}}` would be a variable name and not a file name.

What I want to achieve is to look for the sidebar partial not based on the filename, if I pass to the loader:

```
$partials = array(
    'sidebar' => 'folder1/somefile'
);
```

which would translate to: `views/folder1/somefile.mustache`.

**Comment by boazsegev** [comment]
I know this is an old question, but for the sake of future readers, here's **an easy workaround** using the power of a template and JSON:

Use a "switch" style partial `{{> sidebar_select}}`, with `sidebar_select. mustache`:

```mustache 
{{# sidebar_type}}
  {{# foo}}
    {{> sidebar_foo}}
  {{/ foo}}
  {{^ foo}}
    {{# bar}}
      {{> sidebar_bar}}
    {{/ bar}}
    {{^ bar}}
      {{! ... and so on... until: }}
      {{> sidebar_default}}
    {{/ bar}}
  {{/ foo}}
{{/ sidebar_type}}
{{^ sidebar_type}}
  {{> sidebar_default}}
{{/ sidebar_type}}
```

The JSON could include a value such as `{"sidebar_type"={"sidebar_foo"=true}}`, and that's it... should work with any mustache implementation.
