### ISSUE TITLE
Do not escape HTML

### ISSUE THREAD

**Issue by YoSmudge** [bobthecow/mustache.php#14]
<p>When I do something like<br />
$m-&gt;render('&lt;h1&gt;{{title_plain}}&lt;/h1&gt;{{title_html}}', array('title_plain'=&gt;'Hello World', 'title_html'=&gt;'&lt;h1&gt;Hello World&lt;/h1&gt;'));</p>

<p>it returns<br />
  &lt;h1&gt;Hello World&lt;/h1&gt;<br />
  &amp;lt;h1&amp;gt;Hello World&amp;lt;/h1&amp;gt;</p>

<p>How do I get it to not escape the HTML in the data string?<br />
  -Sam</p>

**Comment by jeliasson** [comment]
For anyone ending up here with node-red and Home Assistant TTS issues, have [a look here](https://community.home-assistant.io/t/help-with-amazon-polly-via-node-red-call-service-tts/67753/10?u=jeliasson).
