### ISSUE TITLE
Add option for throwing an exception on variable "misses"

### ISSUE THREAD

**Issue by rjmackay** [bobthecow/mustache.php#151]
By default when you use a variable that doesn't exist you just get an empty string. It would be great for debugging to have an option to throw exceptions on missing variables.

**Comment by adduc** [comment]
Would you be opposed to having this code snippet added to the wiki somewhere (maybe in a new Examples page)?

**Comment by bobthecow** [comment]
> While the above code works in simple situations, it fails when filters and numeric arrays are involved.

Feel free to improve it and contribute your improvements ;)

**Comment by djibarian** [comment]
Wouldn’t be better to not having to include that big piece of code if the only thing you want is to keep the tag untouched if not defined, or throw an exception if missed? I mean, wouldn’t be easier setting a flag?
