### ISSUE TITLE
Associative arrays

### ISSUE THREAD

**Issue by ghost** [bobthecow/mustache.php#197]
Is there a way to loop over associative arrays?

Thanks

**Comment by devgutt** [comment]
Sorry to reopen an old thread, but this is a problem I am facing right now, and I think the solution that you proposed is not ideal. if I can iterate on a list, I should be able to iterate on a hash array either. Semantically, I think it would be correct to use:

```
 {{# hash_array }}
    {{# . }}
        <p> {{ key }} : {{ value }} </p>
    {{/ . }}
 {{/ hash_array }}
```
