### ISSUE TITLE
Cached class name collisions?

### ISSUE THREAD

**Issue by khromov** [bobthecow/mustache.php#246]
I'm currently writing a cache adapter for mustache.php using the WordPress Object Cache.

That got me looking into how the class names for the cached representations of templates are generated:
https://github.com/bobthecow/mustache.php/blob/master/src/Mustache/Engine.php#L594

I was expecting the template absolute path (on disk) to be part of the calculation, but as it stands right now, two templates that have the same flags and compile to the same content will cause a "class already defined" collision, unless  template_class_prefix is different between the templates?

However, maybe two templates that result in the exact same code isn't really an issue anyway? :)

**Comment by bobthecow** [comment]
Two templates that result in the exact same code are the exact same template, even if you call them by different things :)

**Comment by bobthecow** [comment]
Also, there's no such thing as a "class already defined" collision... it just uses the class if it's there, and doesn't bother compiling the second one.

**Comment by khromov** [comment]
@bobthecow Gotcha! Thanks for the quick reply.

Here's my adapter:
https://github.com/khromov/mustache-wordpress-cache

It was very simple to write, great job on making the API understandable. :+1:

**Comment by bobthecow** [comment]
Nice!

You know, you don't have to use the ugly underscored names... I'm stuck with them because of SemVer, but you can use namespaces like they're intended :)

**Comment by khromov** [comment]
Thanks for the tip!

**Comment by bobthecow** [comment]
Thanks for building the adapter. I've started [a page on the wiki for cache adapters](https://github.com/bobthecow/mustache.php/wiki/Cache-Adapters)

**Comment by khromov** [comment]
Awesome!

What's great about about the WP Object Cache is that it can have different backend - memcached, apc, redis, etc. So it's a catch-all solution.
