### ISSUE TITLE
Precompiling templates to ship?

### ISSUE THREAD

**Issue by Rarst** [bobthecow/mustache.php#247]
I am using the library here and there in my WordPress plugins, some of which are publicly distributed. Since I have no control over target environment there is no confidence about configuring the directory for cache. Still after a while it seems wasteful to only compile on the fly.

On top of my head I could come up with couple of ideas on including and shipping compiled templates:

1. Generate PHP “mirror” of mustache files, have them be looked up before mustache templates by name.
2. Use current cache functionality, but restrict it to read only mode.

Could one of these (or other approach for achieving it) be implemented with current code? Considered as a future feature?

**Comment by bobthecow** [comment]
I'm not sure this is enough of a core use case that I'd ship it in the library, but you could definitely do it on your end.

Do something like this to generate a directory full of precompiled templates:

```php
$myTemplates = ['foo', 'bar', 'baz'];

$m = new Mustache_Engine([
    'loader' => new Mustache_Loader_FilesystemLoader('./templates'),
    'cache' => './precompiled',
]);

$manifest = [];
foreach ($myTemplates as $name) {
    $tpl = $m->loadTemplate($name);
    $manifest[$name] = get_class($tpl);
}

file_put_contents('./precompiled/manifest.json', json_encode($manifest));
```

Then in your shipping code use a custom cache implementation that treats your `precompiled` directory as a read-only cache.

```php
class PrecompiledCache implements Mustache_Cache
{
    protected $manifest;

    /**
     * Load a compiled Mustache_Template class from the precompiled template cache.
     *
     * @param string $key
     *
     * @return boolean indicates successfully class load
     */
    public function load($key)
    {
        if (!isset($this->manifest)) {
            $this->manifest = json_decode(file_get_contents('./precompiled/manifest.json'));
        }

        if (!isset($this->manifest[$key])) {
            return false;
        }

        require sprintf('./precompiled/%s.php', $this->manifest[$key]);

        return true;
    }

    /**
     * This cache is read-only, so if we're asked to cache a new template, just eval it.
     *
     * @param string $key
     * @param string $value
     *
     * @return void
     */
    public function cache($key, $value)
    {
        eval('?>' . $value);
    }
}
```

_Note that I haven't tested or even run the above code. For the purposes of this answer, consider it pseudocode that quite possibly works as real code ;)_

**Comment by Rarst** [comment]
Sorry for slow turnaround, I had read this when you answered, but _just_ got to trying this out in practice.

I will need to sleep on it, but I had arrived on even simpler solution, based on your example:

```php
class Mustache_FrozenCache extends \Mustache_Cache_FilesystemCache {

	public function cache( $key, $value ) {
		eval( '?>' . $value );
	}
}
```

This will function precisely like normal filesystem cache, with only difference that it will never write files. Effectively:

1. I can just use normal instance of filesystem cache to iterate through templates and generate cache files
2. I don't need manifest since it will simply use default file names convention to look up cache entries
3. If anything goes wrong with cache it will just fall back to compiling on the fly

**Comment by bobthecow** [comment]
Sure, that should work, too!

**Comment by bobthecow** [comment]
The one downside would be that they couldn't cache anything new, but that would be the case for my precompiled cache as well.

Note that since you're using the default template class and file names, your precompiled templates will only work with the version of mustache you compile them with. See [`Mustache_Engine::getTemplateClassName`](https://github.com/bobthecow/mustache.php/blob/master/src/Mustache/Engine.php#L594-L606) for the data it hashes to get that name.

Ideally, you should either lock to a specific mustache, or bump the minimum mustache version to the latest every time you commit new compiled templates. You could also keep the old compiled templates around, and just add to the precompiled template cache every time you do a release.

**Comment by Rarst** [comment]
> Note that since you're using the default template class and file names, your precompiled templates will only work with the version of mustache you compile them with. See  Mustache_Engine::getTemplateClassName  for the data it hashes to get that name.

Yeah, I saw that. Might tinker with name generation later, but good enough for now. Since there is still fallback to on the fly compilation, it's safe and no worse than not having cache at all.
