### ISSUE TITLE
show more assoc-array examples in the tutorial

### ISSUE THREAD

**Issue by ppKrauss** [bobthecow/mustache.php#254]
I need to loop as `foreach()` with my array, 

```php
$input = array (
  1 =>   array (    'year' => '1534',    'day' => 'October 13',  ),
  2 =>   array (    'year' => '1644',    'day' => 'September 15' )
  // ...
);
$m->render( $mst, $input );	
```

but can't ref without a "rooot key"... This is the first problem to show in the tutorial. 

Then I use `$input = array('table'=>$input);` and ok, now `table` key exist to 
```
{{#table}} test1 {{/table}}
{{#tableFalse}} test2 {{/tableFalse}}

```
**but it not loops** (!)... shows "test1" once, and ok, no "test2".

**Comment by bobthecow** [comment]
It doesn't loop because you're not entering valid mustache tags. Your template should be `{{#table}}test{{/table}}`

**Comment by ppKrauss** [comment]
ops, sorry, here is wrong (editing) but my code ok,

```
    	x={{teste}}
{{#table}}test1 		{{/table}}
{{#table2}}test2 		{{/table2}}
```

**Comment by bobthecow** [comment]
Can you show me your exact template and rendering code?

**Comment by bobthecow** [comment]
Oh, just kidding. I figured it out. Get rid of the array keys in your table value.

**Comment by ppKrauss** [comment]
... Can you help here? https://github.com/ppKrauss/habemus-papam/blob/master/templates/official.mst 

I run the template with https://github.com/ppKrauss/habemus-papam/blob/master/testkit/php/run.php

**Comment by bobthecow** [comment]
I already answered your question :)

> Get rid of the array keys in your table value.

You shouldn't ever be supplying your own keys for non-associative array.

[Here's why it matters in Mustache](https://github.com/bobthecow/mustache.php/wiki/Mustache-Tags#lists-vs-hashes). In short, PHP only has one data type to use for both "list" and "map" type arrays, so Mustache has to decide whether you mean to use `$input` as an associative array or a list. It decides to iterate if and only if your array has zero-based consecutive integer keys.
