### ISSUE TITLE
Strange indenting issue

### ISSUE THREAD

**Issue by mattdeclaire** [bobthecow/mustache.php#258]
Hi,

I'm seeing a strange issue with indenting, and wanted to see if you've encountered it.
```html
0{AVy0{AVy0{AVy	<a href="/">
0{AVy0{AVy0{AVy		Home
0{AVy0{AVy0{AVy	</a>
```

**Comment by mattdeclaire** [comment]
I don't think this is in the library.  Don't mind me.

**Comment by bobthecow** [comment]
I was going to say, that is weird. What caused it?

**Comment by mattdeclaire** [comment]
We have some corrupted opcode caching issues.  😩
