### ISSUE TITLE
PHP tags to include php code in templates ?

### ISSUE THREAD

**Issue by val4o0o0** [bobthecow/mustache.php#259]
I see in phpbb template system it has  code  tags in template and you can include php code inside them
 = start tag of php <?php
 = ?>

I want to use something else in mustache php, like:
{{php}} {{/php}}

is there any chance to do that?

**Comment by bobthecow** [comment]
Nope. Never :)

What are you trying to solve with this?

**Comment by val4o0o0** [comment]
I try to include some scripts in templates. I have php scripts and its complicated to rewrite to work with mustache (its a lot of time to spend). In phpbb3 i can include everything and its work on their template system without rewriting. 
I was hoping here is the same.
The php scripts is very basic (php/mysql) Without template systems and other hardcode things.

**Comment by bobthecow** [comment]
Executing PHP inside mustache templates is fundamentally opposed to the most central principle of mustache :)

There are ways you can do it, though I wouldn't recommend keeping them around long term. Probably the easiest would be to register a "helper" that's an array of closures which have your custom PHP. Something like this (though I didn't test it at all, it should give you the idea):

```php
$mustache->addHelper('legacy', array(
    'somestuff' => function() {
        return 'some stuff!';
    },
));
```

```html+jinja
{{{ legacy.somestuff }}}
```

**Comment by val4o0o0** [comment]
This is not working with include/require or i dont understanding correctly.
Anyway, i create a private CMS with mustache and i want to adding some modules like sms systems, other systems which is ready, but not written on mustache.

Mustache is great, but maybe its not easy to implement this {{php}}{{/php}} tags that i want, because of its structure ?

I want to use {{php}}include('test.php');{{/php}} in templates file (which have extension .mustache or defined by me)
Because i have admin panel and there users can create custom pages/menus and i want to use this tags to have opportunity to includes some scripts.
The admin panel and all cms is written on mustache, but this scripts that i want to include - not.

**Comment by bobthecow** [comment]
No, it's not that it's not easy to implement `{{php}}{{/php}}` tags, it's that _you're completely missing the point of mustache_ if you're asking for them. _The_ fundamental principle of mustache is that _it's not possible_ to include logic in mustache templates. That's it. That's why you can't do it.

There are plenty of ways to do what you want. I gave you one example with helpers. But the one way you'll never be able to do it in mustache is to execute arbitrary code :)

**Comment by bobthecow** [comment]
```php
$mustache->addHelper('legacy', array(
    'test' => function() {
        ob_start();
        include 'test.php';
        return ob_end_clean();
    },
));
```

```html+jinja
{{{ legacy.test }}}
```

**Comment by val4o0o0** [comment]
@bob, i test this last piece of code - but not working. It shows '1' everytime. I create test.php with only text, but when i include it shows '1'. (maybe 'true')

I understand the work of the Mustache, but secretly I am hoping that there is an option :)

Thanks for your help! Iframes is variant, but ... (sucks) :) 
Anyway, I wish you all the best, good luck!

**Comment by bobthecow** [comment]
Oh, sorry, that should have been `ob_get_clean()` not `ob_end_clean()`. The second one discards the buffer :)

**Comment by bobthecow** [comment]
![test](https://cloud.githubusercontent.com/assets/53660/7896003/ce9aa99c-065e-11e5-91ae-768498f24cb7.png)

**Comment by gburtini** [comment]
Is there a prescribed method of providing transformations of data?

For example, I'm using Mustache to render table cells from a template at the moment. The data comes in via a blackbox API and I pass it straight in to Mustache. This means that sometimes data is in user-unfriendly formats like unix timestamp. I want to provide a constrained set of transformation methods that is allowed in the template, for example timeToFriendlyDate({{timestamp}}).

**Comment by bobthecow** [comment]
Sorry, I didn't notice the response on this issue.

The prescribed method for providing data transformations in Mustache is not to pass your data straight into Mustache. See [this answer on StackOverflow](http://stackoverflow.com/questions/12358228/mustache-php-idiomatic-ways-to-template-select-dropdowns/12753087#12753087) for a way to prepare your data using ViewModels.
