### ISSUE TITLE
Class methods in templates do not get passed parameters

### ISSUE THREAD

**Issue by bajax** [bobthecow/mustache.php#260]
I'm having some trouble right now--I've got a view class, which is loaded up with helper methods to assist the template in rendering a particularly complex HTML table.  This setup has worked great for me up until I needed to be able to use Mustache's lambda functionality (IE receiving the $text and $context variables as parameters)

When my context object is a class, and the helpers methods,it doesn't pass any parameters.  For example, this will never work:

	class Foo
	{
		function bar($text, $context)
		{
			//this will never run--missing required parameters
		}
	}

One weird thing is that this works perfectly fine:

	class Foo
	{
		public $bar;
		__construct()
		{
			$self = $this;
			$this->bar = function ($text, $context) use ($self) 
			{
				//works great
			};
		}
	}

Is this the intended behavior?

Edit 1:
Another strange thing I just discovered--this works as well:

	class Foo
	{
		function _bar ($text, $context)
		{
			//works great....  WHY?
		}
		function bar ()
		{
			return [$this, '_bar'];
		}
	}

PHP's anonymous function syntax is bizarre.  

Edit 2:
Well, I've figured out why they don't work.  It has to do with the fact that in PHP methods/functions aren't first class objects, only represented by "callables," that get looked up on execution, and instance methods are treated differently from static methods and normal functions.   I apologize for the proliferation of edits on this issue.

**Comment by bajax** [comment]
Another strange thing I just discovered--this works as well:

	class Foo
	{
		function _bar ($text, $context)
		{
			//works great....  WHY?
		}
		function bar ()
		{
			return [$this, '_bar'];
		}
	}

PHP's anonymous function syntax is bizarre.

**Comment by mattdeclaire** [comment]
I believe you need to return a function from the class method:
```php
class Foo
{
   function bar()
   {
      return function($content, $helper) {
         $text = $helper->render($content);
         return strtoupper($text);
      };
   }
}
```

**Comment by bajax** [comment]
@mattdeclaire That's a brilliant solution.  I don't know why I didn't think of it.  Thanks.

**Comment by bobthecow** [comment]
@bajax What you were missing is that if the *value* of a tag is a function, then it's treated as a lambda.

Meaning:

```php
$a = new StdClass;
$a->foo = function($text, $helper) {...}; // this is a lambda
// ... because `$a->foo` is a property whose value is a function.

class B {
  function __construct() {
    $this->foo = function($text, helper) { ... }; // this is a lambda
    // ... for the same reasons as above.
  }

  function bar() {
    // this is not a lambda, it's a getter.
  }

  function baz() {
    // this, too, is a getter, but it returns a lambda :)
    return function() { ... }; // see, here's the lambda!
    // ... because the result of calling the `$b->baz()` getter is a lambda.
  }
}

// and, depending on your Mustache settings...
$b = new B;
$b->qux = [$b, 'bar']; // this is also a lambda

// ... this last one is weird, until you consider that in PHP,
// an array with `[$object, 'methodName']` is just as "callable"
// as an anonymous function :)
```
