### ISSUE TITLE
Sections with unknown but callable (lambda) values?

### ISSUE THREAD

**Issue by markzero** [bobthecow/mustache.php#262]
I'm curious if there is possibility to have yet undefined values inside sections, but get them later when you know it's key? If it's unclear follow example below:

Suppose you have a section:

```
{{# user.meta }}
<p>Username: {{ username }}, role: {{ role }}</p>
{{/ user.meta }}
```

And then in PHP you get field called "username" of e.g. user object:

```
array('user' => array(
    'meta' =>  function($text) {
        // ... e.g. read from database 
        // $text here will be "<p>Username: {{ username }}</p>"
    })
);
```

So, what I was basically trying to do is extract with preg_match anything between {{...}} and use that value (in this case "username" or "role") as key for values I'd like to get and return it as array as ["username" => "marko", "role" => "admin"]. I succeeded but then returned value is not array but closure.

Also, reason for this is that I can load data from DB inside "user" array, but what if there's plenty of records, i.e. thousand -- don't want to load all, but only ones I need, on-the-fly.

Any suggestions, tips & tricks??? I believe this must be possible somehow! :)

**Comment by bobthecow** [comment]
It seems like this would be a perfect use case for using an actual view model, rather than an associative array? Write a class that wraps your user data (say, `UserViewModel`), have methods for any of the values you want to lazily load, and pass everything else through to the underlying array data (or data model, if you've got one) via `__isset` and `__get` calls.

**Comment by markzero** [comment]
Seems so, but we don't even know the key, so it would be great for key/value pairs from database.
 
Pseudo code would be like: select username from user where id = current_user.id; where current_user is some global you don't care..

**Comment by ivantcholakov** [comment]
I can imagine generation of the template itself dynamically, at the moment the keys are known. Not elegant, but possible.

**Comment by markzero** [comment]
What I achieved so far is:

```
class Myclass {
    function __isset($_key) {
        $_val = get_value($_key);
        $this->$_key = $_val;
    }
}
```

And when building array:

```
class Metas {
    public function build() {
        $obj = new Myclass();
        $this->parts['meta'] = $obj;
    }
}
```

Downside is that I have to call mustache dot notation twice for some value - first time it sets it (isset is called too late) and second time object now has this value and can be displayed:

```
<p style="color:green;">{{ user.meta.city }} {{ user.meta.city }}</p>
```

Thoughts??

**Comment by bobthecow** [comment]
You need to return `true` from `__isset` so that it knows you found a value for the key. Or, return `false` if you didn't. That's what `__isset` is supposed to do ;)

**Comment by markzero** [comment]
Obviously!! :D Thanks a lot, it works now! So the same code as above only with return true;  as 3rd line in __isset function :) works great

**Comment by bobthecow** [comment]
Great!
