### ISSUE TITLE
Don't htmlspecialchars content

### ISSUE THREAD

**Issue by markzero** [bobthecow/mustache.php#263]
Is there a way not to do `htmlspecialchars` on returned content from lambda functions?

I return e.g. `$content . '<a href="...">link</a>'` and mustache.php converts to HTML entities like &amp;gt; or &amp;lt; etc.

**Comment by markzero** [comment]
I figured just to pass `escape` param to constructor:

```
        $m = new \Mustache_Engine(array(
            'escape' => function($value) {
                return $value;
            }
        ));
```

**Comment by bobthecow** [comment]
Lambdas follow the same rules for escaping as everything else. For lambda sections, no additional escaping is done. Whatever you return from the function is rendered as is. For lambda interpolation tags, use triple mustaches to prevent escaping.

```php
<?php

require './vendor/autoload.php';

$m = new Mustache_Engine();

$data = [
  'foo' => function($str) {
    return $str . '<a href="#">link</a>';
  },
  'bar' => function() {
    return '<b>wat</b>';
  }
];

echo $m->render('{{# foo }}FOO{{/ foo }} {{ bar }} {{{ bar }}}', $data);
```

Result:

```
FOO<a href="#">link</a> &lt;b&gt;wat&lt;/b&gt; <b>wat</b>
```
