### ISSUE TITLE
Problem with array index containing period

### ISSUE THREAD

**Issue by Marcel-Robitaille** [bobthecow/mustache.php#266]
I have an array with all of the cache-busted names for my stylesheets. 

````
$manifest = [
    'style.css' => 'style-ab92e5ec.css'
}
````

I am passing the array to mustache.
When I try to include the file like this:
````
<link rel="stylesheet" href="css/{{#manifest}}{{style.css}}{{/manifest}}">
````
The dot before css is interpreted as an array using dot notation:
````
$manifest = [
    'style' => [
        'css' => ''
    ]
]
````

I have tried escaping the dot using several methods but none are working.
Please help.

**Comment by bobthecow** [comment]
There are literally only two things your array indices can't contain: `.` and `}}`. Pre-process your data and use something else :)

**Comment by Marcel-Robitaille** [comment]
No way to encode the .? Ok, I will pass in a modified $manifest. Thanks.

**Comment by bobthecow** [comment]
Yeah, mustache doesn't (currently?) have any concept of escaped or encoded characters, because other than this specific case, there's not much use for 'em.
