### ISSUE TITLE
Get index form new ArrayIterator

### ISSUE THREAD

**Issue by oknoorap** [bobthecow/mustache.php#267]
Is php support @index syntax? I've tried to display index by adding {{@index}} in template loop but it's blank.

example:
```
{{#array}}
	{{@index}}
{{/array}}
```

Actually, in js it's works.

**Comment by bobthecow** [comment]
No, that's not part of mustache. You can wrap your arrays (or arrayiterators) in a presenter to expose things like that if you like. See an example here: https://gist.github.com/bobthecow/61161639d8be82a75b5e#file-iteratorpresenter-php
