### ISSUE TITLE
A bug of render

### ISSUE THREAD

**Issue by treemonster** [bobthecow/mustache.php#269]
// D:\demo\code\public\vc\Mustache.php 

<?php 

function mustache_autoload($class_name){
  require_once(\_\_DIR\_\_.'/'.str_replace('_','/',$class_name).'.php');
}
spl_autoload_register('mustache\_autoload');
$m = new Mustache\_Engine;
 echo $m->render('
\{\{\#musketeers}}
\* \{\{.\}\}
\{\{/musketeers\}\}
 ',array(  
###  // when count is two , it will occur a strange error
    "musketeers"=> ["Athos","zxs"]  
  
  
  )
);

Warning: require_once(D:\demo\code\public\vc/Athos.php): failed to open stream: No such file or directory in D:\demo\code\public\vc\Mustache.php on line 3

Fatal error: require_once(): Failed opening required 'D:\demo\code\public\vc/Athos.php' (include_path='.;C:\php\pear') in D:\demo\code\public\vc\Mustache.php on line 3

**Comment by lode** [comment]
See the [`strict_callables`](https://github.com/bobthecow/mustache.php/wiki#strict_callables) option. Right now, your array is seen as callable and your autoloader tries to load a file `Athos` with method `zxs`.

If you set this option to false, your situation will work. From Mustache 3.x this will be the default.

**Comment by bobthecow** [comment]
What @lode said. If you're using PHP 5.3+, you should turn on `strict_callables` and pass closures when you need a lambda section.

You could also solve the problem by using proper autoloader. If you're trying to autoload just Mustache, then use the autoloader that ships with it ([see Autoloader.php](https://github.com/bobthecow/mustache.php/blob/master/src/Mustache/Autoloader.php)). If you're autoloading more libraries, use the autoloader that ships with Composer or another well-tested community built autoloader.

You should do this regardless of whether you turn on `strict_callables` or not :)
