### ISSUE TITLE
Question: 5.2 support

### ISSUE THREAD

**Issue by keradus** [bobthecow/mustache.php#270]
Hi!
Is there any time when you plan to drop support for (so old and not maintained anymore) PHP 5.2 ?

**Comment by bobthecow** [comment]
We'll drop support for 5.2 in v3.0 (the next major version).

**Comment by keradus** [comment]
Does next major version even planned?

**Comment by bobthecow** [comment]
Not yet :)

**Comment by keradus** [comment]
Then, maybe we could move into 5.3+ and leave 5.2, which is already dead? It will allow us to move forward with the code itself.
And if someone still uses so-old 5.2, then in fact he didn't want to use latest mustache ;)

**Comment by bobthecow** [comment]
Meh. There's no extra work to support 5.2, because it already works. There's really no upside to rewriting just for the sake of rewriting. That's why it's not happening until the next major version.

**Comment by keradus** [comment]
:(
