### ISSUE TITLE
Non-False Values

### ISSUE THREAD

**Issue by designermonkey** [bobthecow/mustache.php#271]
I have a setup that has a custom `ArrayObject` as our array-like data, and these are nested.

I'm trying to implement the non false values from the wiki,

```
    {{# content.first-image? }}
    <figure>
        <img src="{{ image }}" alt="{{ alt-text }}">
    </figure>
    {{/ content.first-image? }}
```

`first-image?` is an array-like object that has about 5 properties in it. When we do this, all that happens is that 5 x `figure` elements are output, as it is just looping over the array-like object, not as expected from the wiki explanation.

Is this expected? Have I read it wrong?

I would expect that if `first-image?` is `null` or `false` it would ignore it, but if it had a value, then adjust the context, not loop.

**Comment by bobthecow** [comment]
That's exactly the expected behavior. In mustache, a section tag — like `{{# foo }}` — is rendered zero or more times. If the value is null or falsey, it's rendered zero times. If the value is an array or traversable object, it's rendered multiple times, once per element in the iterable. Otherwise, the value is used as the rendering context for the section. See the wiki for more on sections: 

https://github.com/bobthecow/mustache.php/wiki/Mustache-Tags#sections

**Comment by designermonkey** [comment]
So, is the question mark part of the templating language, or just not relevant at all?

**Comment by designermonkey** [comment]
I'm basing this on: https://github.com/bobthecow/mustache.php/wiki/Mustache-Tags#non-false-values

**Comment by designermonkey** [comment]
Ahhh, I think I get you now, so, as my object is traversable, even though it is an associative array, it is iterated. So the difference is between an associative array, and a numeric array and an iterable associative array-like-object. Is that right?

**Comment by bobthecow** [comment]
The question mark is just part of the key in that array, it's not relevant at all. That example would probably be clearer without it :)

> When the value is non-false but not a list, it will be used as the context for a single rendering of the block.

The "but not a list" bit there is the important part. If your thing is an ArrayObject, it's considered a list, so it's rendered multiple times, once per element in the array.

**Comment by bobthecow** [comment]
Yep! Looking back through the documentation, that bit is not super clear. It talks about the difference between associative arrays and numeric arrays, but doesn't make it clear that this is array primitives, and that array-like objects determine whether they're iterable based on Traversable.

**Comment by designermonkey** [comment]
Thanks for the clarification. All part of learning.

**Comment by bobthecow** [comment]
It's at least partially mustache's fault. If you can think of a way to improve the documentation to save future people from the same misunderstanding, we'd welcome the contribution :)
