### ISSUE TITLE
Return array from lambda

### ISSUE THREAD

**Issue by markzero** [bobthecow/mustache.php#272]
Is it possible to get array from lambdas? 

Say I have array to build for output like:

```
$array['colors'] = function() {
    return array('r' => 'red', 'g' => 'green', 'b' => 'blue');
};
```

For this I get output just as "Array" and warning:
Warning: strpos() expects parameter 1 to be string, array given in ...

**Comment by bobthecow** [comment]
Nope. Use a class for your view model rather than an associative array :)

**Comment by bobthecow** [comment]
This is essentially the same question you asked in #262, right? Did that solution not work for you?

**Comment by markzero** [comment]
Yeah but then have to create class for each case, which is not big deal but can escalate :) just wanted to make sure if it's possible with arrays.. thanks.

**Comment by markzero** [comment]
Closing this issue since there's probably no solution at least for now.
