### ISSUE TITLE
Question about Inverted Sections

### ISSUE THREAD

**Issue by designermonkey** [bobthecow/mustache.php#273]
I get how inverted sections work, for rendering something when a value doesn't exist, but what does it set the context to?

```html
<img {{# thumbnail }} src="{{ . }}"{{/ thumbnail }}{{^ thumbnail }} src="{{ source }}"{{/ thumbnail }} alt="{{ alt-text }}"/>
```

`thumbnail` and `source` are at the same level in the context, yet I don't seem to be able to get `source` to output in this example.

Any suggestions as to what I should do?

**Comment by bobthecow** [comment]
Do you mind providing sample data so I can have a better idea what's going on?

**Comment by designermonkey** [comment]
Certainly, here is some raw json from our database. We mung this into an ArrayObject to process.

```json
[{"image":{"thumbnail":null,"source":"/assets/uploads/books/560313d04b592.jpg","alt-text":"Al Text Here","caption":null,"credit":{"text":null,"link":null}}}]
```

**Comment by designermonkey** [comment]
A colleague figured out that we had an errant data structure, and weren't at the correct context level.

It does indeed work fine, and leaves the context at the right level.

Sorry to have wasted your time here @bobthecow

**Comment by bobthecow** [comment]
Good to hear! No worries, I'm glad you were able to get it resolved.
