### ISSUE TITLE
Relative paths for partials in partials

### ISSUE THREAD

**Issue by nebulousGirl** [bobthecow/mustache.php#274]
I use my templates both with mustache.php and mustache.js

In mustache.js, partials load relative to the current file, but in mustache.php, partials are always loaded from the views main directory.

Is there a way to load partials relative to the current file? I would prefer this to the current behavior.

**Comment by nebulousGirl** [comment]
I was able to adapt mustache.js to behave the same as mustache.php

**Comment by bobthecow** [comment]
:+1: great!
