### ISSUE TITLE
Context gone after use

### ISSUE THREAD

**Issue by designermonkey** [bobthecow/mustache.php#277]
I've come across an issue where I need to re-use the same context repeatedly throughout a template. I give a div the same data attribute from a configuration.

To do this, I use a template that I call in to the document

```
{{> partials/ads/home/mobile }}
```

And inside it I do the following

```
{{# adverts.external.home.mobile }}
    <div data-advert-id="{{ advert-id }}"></div>
{{/ adverts.external.home.mobile }}
```

This works ok the first use, but next time the template is called, the context no longer exists, and so nothing is rendered.

I really hope this is a bug, and not expected behaviour, as this is a real problem for me (especially 98% way through a 6 month project).

**Comment by bobthecow** [comment]
I'm afraid I'll need a bit more information to understand what's going on. Can you add a code sample that reproduces what you're seeing?

**Comment by designermonkey** [comment]
That may take a while, I have to pull it all apart. Bear with me...

**Comment by Chemaclass** [comment]
@designermonkey did you call the variable name as `advert-id` with `-`?

**Comment by designermonkey** [comment]
Yeah, but this works fine, as it is in other contexts I have.

Rather weirdly, this template never shows, and others used in exactly the same way show randomly in some places, but not others.

I'll get this example working this morning.

**Comment by designermonkey** [comment]
Ok, I've put a test together, and even used the same complexity of the blocks pragma, folder structure etc that's in the original project, and it doesn't do the same thing.

I think the code is conspiring against me at the moment :(

**Comment by designermonkey** [comment]
I'm going to close this issue. A colleague has stepped through the data with me and found the flaw at our end.

Two heads are better than one, obviously.

Thanks for your time.

**Comment by bobthecow** [comment]
No worries. Glad you were able to find it.
