### ISSUE TITLE
"Warning: htmlspecialchars() expects parameter 1 to be string, object given" error when passing in an object.

### ISSUE THREAD

**Issue by hellopablo** [bobthecow/mustache.php#278]
I'm getting the above error when attempting to query the existence of a property and/or render it.

I'm passing an `stdClass()` object into `render()` which looks something like this:

    stdClass Object
    (
        [sentTo] => stdClass Object
            (
                [id] => 1
                [email] => pablo@example.com
                [firstName] => Pablo
            )
        [email_subject] => Reset your Password
    )

The erroring part of my Mustache template looks like this:

    {{#sentTo.firstName}}
        <p>
            Hi {{sentTo.firstName}},
        </p>
    {{/sentTo.firstName}}

Which raises the following error:

    A PHP Error was encountered
    Severity: Warning
    Message: htmlspecialchars() expects parameter 1 to be string, object given
    Filename: /Users/pablo/Sites/example/vendor/mustache/mustache/src/Mustache/Cache/NoopCache.php(45) : eval()'d code
    Line Number: 559

The following also causes the error:

    {{#sentTo}}
        <p>
            Hi {{sentTo.firstName}},
        </p>
    {{/sentTo}}

Am I doing something wrong here? Or using Mustache as it shouldn't be used. Interestingly, the output is correct, but the errors are annoying and cause other bits of the application flow to trip up

**Comment by hellopablo** [comment]
Ignore me. Was elsewhere in the template, and a valid face-palm on my part. 😁

**Comment by bobthecow** [comment]
Heh. No worries :)
