### ISSUE TITLE
Query on wiki example

### ISSUE THREAD

**Issue by alexryderwhytewaters** [bobthecow/mustache.php#279]
I am only just starting with mustache, so I might have this wrong, 
but I would have expected the output to be

WILLY is awesome.

Not 

WILLY IS AWESOME.

Example Code
Data:

<?php
array(
  'name' => "Willy",
  'embiggened' => function($text, Mustache_LambdaHelper $helper) {
    return strtoupper($helper->render($text));
  }
);
Output:

WILLY IS AWESOME.

**Comment by bobthecow** [comment]
Lambdas are called on the entire section, not just on the tags inside the section, e.g. with this template:

```html+jinja
{{# embiggened }}
  {{ name }} is awesome.
{{/ embiggened }}
```

The `embiggened` helper is passed `"{{ name }} is awesome."` as `$text`. We then render it:

```html
$helper->render($text)
```

… which results in `"Willy is awesome."`, and pass the result of that to `strtoupper`, resulting in the final output:

```
WILLY IS AWESOME.
```

Make sense?
