### ISSUE TITLE
Accessing an key of array with spaces

### ISSUE THREAD

**Issue by iron1902** [bobthecow/mustache.php#280]
This does not work:
{{translate.["Invoice Nr."]}}

http://stackoverflow.com/questions/14269989/access-array-key-with-space

**Comment by bobthecow** [comment]
`{{# translate }}{{ Invoice Nr. }}{{/ translate }}` should do it.

**Comment by bobthecow** [comment]
(If this didn't do it for you, please feel free to re-open)
