### ISSUE TITLE
How check if all variables is set 

### ISSUE THREAD

**Issue by Ducatel** [bobthecow/mustache.php#284]
Hi all,

I want to known if all variables present in a template is present during the rendering.

```php
$mustacheEngine =  new Mustache_Engine();
$result = $mustacheEngine->render("testing {{ templateEngine }}", []); 
```

For example, in this code, the render should be fail / throw an exception (or something else) because the variable `templateEngine` is missing.

So how I can know that ?

Thanks in advance for your help.

**Comment by Chemaclass** [comment]
Hallo! You can check if one variable exists with one simple condition as:
{{#templateEngine}} {{.}} {{/templateEngine}}

**Comment by Ducatel** [comment]
Hi Chemaclass,
I don't want to check that in the template, I want to check in the PHP code.
( Because, I cannot manage the template in entry of my PHP function )

**Comment by bobthecow** [comment]
Something like this should do the trick:

<img width="762" alt="screen shot 2016-02-10 at 2 03 17 am" src="https://cloud.githubusercontent.com/assets/53660/12944210/8496ca3c-cf9a-11e5-9b20-52913c51be1d.png">

```php
class ThrowyThing {
  private $context;

  public function __construct($context = []) {
    $this->context = $context;
  }

  public function __isset($name) {
    if (!array_key_exists($name, $this->context)) {
      throw new InvalidArgumentException("Missing $name");
    }

    return true;
  }

  public function __get($name) {
    return $this->context[$name];
  }
}

$m = new Mustache_Engine();

$m->render("test {{foo}}", new ThrowyThing(['foo' => 'BAR']));
$m->render("test {{foo}}", new ThrowyThing([]));

$m->render("{{#a}}{{b}}{{/a}}", new ThrowyThing(['a' => ['b' => 'C']]));
$m->render("{{#a}}{{b}}{{/a}}", new ThrowyThing(['a' => ['d' => 'E']]));
```

**Comment by Ducatel** [comment]
It's exactly that. Thanks bobthecow ;)

**Comment by bobthecow** [comment]
No problem :)

**Comment by SaikumarChintada** [comment]
How to handle this case ?
```$m->render("{{#a}}{{b}}{{/a}}", new ThrowyThing(['b' => ['d' => 'E']]));```
