### ISSUE TITLE
Make Mustache_LambdaHelper invokable

### ISSUE THREAD

**Issue by Svish** [bobthecow/mustache.php#285]
Suggestion to make the `Mustache_LambdaHelper` class ["invokable"](http://php.net/manual/en/language.oop5.magic.php#object.invoke)? Would make lambda's and such a tiny bit cleaner, which I like, and very simple to do:

**Added to `Mustache_LambdaHelper`**
```php
/**
 * Alias of render(string).
 */
public function __invoke($string)
{
    return $this->render($string);
}
```

Should be backwards compatible and works for PHP>=5.3. The wiki says the mustache code works for PHP>=5.2, but don't think this would break that. It just wouldn't be usable for that version.

**Example usage**
```php
$engine->render('foobar', [
	'upper' => function($text, $render)
		{
			return strtoupper($render($text));
		},
	]);
```

**Comment by bobthecow** [comment]
:+1: This has been added to the `dev` branch and will go out in the next release.
