### ISSUE TITLE
Padding incorrectly added to lambda values in partials

### ISSUE THREAD

**Issue by Svish** [bobthecow/mustache.php#286]
Think I've found a bug. Given this lambda passed in:

```php
$engine->render('template', [
	'test' => function($text=null) { return 'foo'; },
]);
```

This template:

```html
	"{{test}}"
	{{>partial}}
```

And this partial:

```
"{{test}}"
```
Renders into this:

```
	"foo"
	"	foo"
```

As you can see the value gets padded, seemingly with same padding as the partial gets itself.

Changing partial to this:

```
"{{#test}}{{/test}}"
```

It renders correctly:

```
	"foo"
	"foo"
```

Both should generate the same result, shouldn't they? So... seems like a bug :confused:

**Comment by bobthecow** [comment]
You're right, good catch!

There's a fix in `dev`, it'll go out in the next release.

**Comment by Svish** [comment]
Nice! Any date on the next release? Is there a roadmap type thing somewhere?

**Comment by bobthecow** [comment]
v2.10.0 has shipped!

**Comment by Svish** [comment]
@bobthecow Is something missing for it to appear on [packagist](https://packagist.org/packages/mustache/mustache)?

**Comment by bobthecow** [comment]
Nah, something must have gotten stuck. I kicked it and it worked :)

**Comment by Svish** [comment]
Fantastic! Thank you :smile:
