### ISSUE TITLE
Source templates loaded each time in production

### ISSUE THREAD

**Issue by thewilkybarkid** [bobthecow/mustache.php#290]
While profiling an application I noticed that the library loads the source template each time (the page had ~13ms inside `file_get_contents()` triggered through the template loader), and uses it as part of the hash used as the compiled template name. This means that if you change a template, for example, the changes are visible immediately.

Obviously this is useful in development, but in production this should be unnecessary (clearing caches would be a deployment step). It would be useful to have an option to not recompile templates (the main change presumably being the compiled name being derived from the source name, not the source contents).

This would give a slight performance boost (especially if the cache is warmed during the deployment process, so the source templates are never loaded during runtime).

**Comment by bobthecow** [comment]
Yep, this seems reasonable. And it looks like it could be accomplished — and be completely backwards compatible — by adding a new loader and six lines of code in the engine](6aa91be197b483f8a089efadf39119f1bf1c5cd8). Do you want to check out the `feature/production-filesystem-loader` branch and see if it'll work for you?

**Comment by thewilkybarkid** [comment]
Nearly! `Mustache_Engine::compile()` needs to take the `Mustache_Source` so that the call to `getTemplateClassName()` produces the right class name (or pass the class name as a parameter). At the moment it generates a file with the class name based on the filename, but containing a class with the name based on the source, causing a fatal error as the class can't be found. I quickly fiddled the code to do that and the rest seems to work as expected, thanks.

**Comment by bobthecow** [comment]
Good catch. I supposed I should have tested all the way through render, but I stopped once I got to a compiled file :)

The branch has been updated with that fix, plus has a test case verifying that it works all the way through. Check it out?

**Comment by bobthecow** [comment]
Heh. Actually, this doesn't work (completely). Two files the same size, with the same mtime (e.g. if they're all touched within the same timestamp) will end up with the same template class name. Gotta get the filename in there for good measure :)

**Comment by bobthecow** [comment]
Alright. Fixed for reals this time.

**Comment by thewilkybarkid** [comment]
Looks good!

(I wouldn't need the use of `stat()` to generate the key in production, only the filename... but the overhead should be negligible. Plus I could always use a different implementation.)

**Comment by bobthecow** [comment]
This is a good point. I've added an option to override the `stat()` properties used to invalidate the template cache in 335507456f64529122bd3c24c0711cd3d432f4f8

By default, it will continue to use `size` and `mtime`, but if the option is set to `null` or `[]`, it will not call `stat()` at all.

**Comment by thewilkybarkid** [comment]
Just spotted this was released, thanks.
