### ISSUE TITLE
fix /src/Mustache/Compiler.php

### ISSUE THREAD

**Issue by anatoliWeb** [bobthecow/mustache.php#294]
Fix line 460
$context->pushBlockContext($newContext);
changed to
if(empty($newContext))$newContext = array();
$context->pushBlockContext($newContext);

**Comment by bobthecow** [comment]
What does this fix?

**Comment by anatoliWeb** [comment]
when mustache generate code i have  
public function block7972b8cf96c03e5d0edc9a616a7ee9f0($context)
    {
        $indent = $buffer = '';
        $buffer .= $indent . '    <div class="container main-content">
';
        $buffer .= $indent . '        <ul class="nav nav-tabs nav-menu" role="tablist">
';
        // 'services.avia' section
        $value = $context->findDot('services.avia');
        $buffer .= $this->section9f94f4fd62d09ea89391b986b3b07980($context, $indent, $value);
        // 'services.train' section
        $buffer .= $indent . '        </ul>
';
        $buffer .= $indent . '
';
        $buffer .= $indent . '        <div class="tab-content tab-content-main">
';
        $buffer .= $indent . '            <div role="tabpanel" class="tab-pane active" id="avia-tickets">
';
        $buffer .= $indent . '                ';
        
        
        if ($parent = $this->mustache->LoadPartial('page/avia/_avia_tickets')) {
            $context->pushBlockContext($newContext);
            $buffer .= $parent->renderInternal($context, $indent);
            $context->popBlockContext();
        }

I do not have $newContext and I see an error.

**Comment by bobthecow** [comment]
Can you show me the template which caused this? I'm having a hard time reproducing it.

**Comment by anatoliWeb** [comment]
Exemple: 3 file 

<!DOCTYPE html>
{{% BLOCKS }}
<html lang="{{lang}}">
    <body>
		{{$ header }}{{/ header }}
        
        {{$ content }}{{/ content }}
        {{$ scripts }}{{/ scripts }}
    </body>
</html>

------------- content -----------
{{% BLOCKS }}
{{< layout }}

	{{$ header}}
		{{< page/avia/_avia_tickets }}{{/ page/avia/_avia_tickets }}
	{{/ header}}

	{{$ content}}{{/ content}}
{{/ layout }}

-------------- _avia_tickets ----------

only text 

--------------------------------------- end ------------------------------------------

**Comment by bobthecow** [comment]
Thanks. In this case you should probably be using `{{> page/avia/_avia_tickets}}` inside that header block, but I think I see the problem.

**Comment by bobthecow** [comment]
Okay. This should be fixed in `dev`. Mind grabbing the branch and giving it a try?

**Comment by bobthecow** [comment]
Feel free to re-open if your issue isn't completely fixed :)

**Comment by anatoliWeb** [comment]
These fixes have not been put in by a new version?

**Comment by bobthecow** [comment]
The fix is in v2.11.0
