### ISSUE TITLE
Bug ? 

### ISSUE THREAD

**Issue by val4o0o0** [bobthecow/mustache.php#296]
My CMS on mustache is finished and working well (soon will be written in MVC), but maybe i found a bug. I don't know and i'm not sure on 100%, but maybe is a bug.
The system is integrated with phpbb (fully), their integration is not based on $_SESSION. phpbb don't use $_SESSION, they using self made sessions. (this is written by their dev team)

Now, on the problem... When i'm browsing on site and have 2-3 users online except me, sometimes my 'session' is transferred to another user session. (i get their usernames and information like pm count and other...)
This is very very rare situation... And i don't know, maybe is hosting problem (I/O problem and mustache can't generate proper cache files or can't read them correctly)
I decided to write here to ask whether such problem can be happen from bad server hosting?
The hosting is shared hosting and have SSD's both for mysql/files.
This about sessions... I mentioned it because I'm not sure that Mustache work with them for cache files to pass correctly information to users.

Here is integration:
```
<?php
  define('IN_PHPBB', true);
  $phpbb_root_path = (defined('PHPBB_ROOT_PATH')) ? PHPBB_ROOT_PATH : __DIR__.'/../'.$forum_path;
  $phpEx = substr(strrchr(__FILE__, '.'), 1);
  require($phpbb_root_path . 'common.' . $phpEx);
  require($phpbb_root_path . 'includes/functions_display.' . $phpEx);
  require($phpbb_root_path . 'includes/functions_user.' . $phpEx);
  $user->session_begin();
  $auth->acl($user->data);
  $user->setup();
  $request->enable_super_globals();
  
  //we need it for db connection
  require(__DIR__.'/../'.$forum_path.'config.php');
  $bb_db = $dbname;
  $bb_prefix = rtrim($table_prefix, '_');
  
  //global vars for 3.1
  $bb_is_anonymous = ($user->data['user_id']==ANONYMOUS);
  $bb_session_id = $user->session_id;
  $bb_user_id = $user->data['user_id'];
  $bb_is_bot = $user->data['is_bot'];
  $bb_mail = $user->data['user_email'];
  $bb_username = $user->data['username'];
  $bb_is_admin = $auth->acl_get('a_user');
  $bb_user_ip = $user->ip;
  $bb_user_sig = $user->data['user_sig'];
  $bb_bbcode_uid = $user->data['user_sig_bbcode_uid'];
  $bb_bbcode_bitfield = $user->data['user_sig_bbcode_bitfield'];
  $bb_user_last_visit = $user->data['user_lastvisit'];
  $bb_user_color = $user->data['user_colour'];
  $bb_current_page = $user->page['page'];
  $bb_new_pm = $user->data['user_new_privmsg'];
  $bb_unread_pm = $user->data['user_unread_privmsg'];
  $bb_user_posts = $user->data['user_posts'];
  $bb_user_ava = $user->data['user_avatar'];
  $bb_group_id = $user->data['group_id'];
  $bb_ava_type = $user->data['user_avatar_type'];
```

The variabls with $bb_ - I use them in template files and in backend core files. 

Link to last version - https://drive.google.com/file/d/0B0_5EuRDzdxyN05KZktEZ3I5b0k/view

**Comment by val4o0o0** [comment]
Confirmed: It's a hosting problem.

**Comment by bobthecow** [comment]
Glad you got it sorted out :)
