### ISSUE TITLE
Generated cache filename and class name

### ISSUE THREAD

**Issue by taviroquai** [bobthecow/mustache.php#298]
Hi,

I'm getting generated cache filenames and class names starting with numbers which throws PHP error.

Thanks

**Comment by taviroquai** [comment]
I had the option 'template_class_prefix' = ''

It can be closed or you may consider an alterative in case user emptys this option.

**Comment by bobthecow** [comment]
Oh. Yeah. You probably shouldn't set it to an empty string :)
