### ISSUE TITLE
Feature Request: Root scope

### ISSUE THREAD

**Issue by designermonkey** [bobthecow/mustache.php#299]
With the following in mind:

```php
<?php

$arr = [
    'content' => [
        'brand' => [[
            'logo' => [...]
        ]]
    ],
    'relations' => [
        'pages' => [[
            'content' => [...]
        ]]
    ]
];
```

```
{{# relations.pages.0 }}
<img src="{{ content.brand.0.logo.source }}" alt="{{ content.brand.0.name }} Logo" />
{{/ relations.pages.0 }}
```

When trying to access the content of the parent scope, the content of the current scope takes over.

Is there a way we could add a way to always force starting from the root scope? I know currently the code crawls back up the scope until it finds a matching key, but root scope access would be immense.

**Comment by bobthecow** [comment]
There isn't a way to do this in Mustache, though there have been some suggestions around this and similar issues (accessing parent scope, etc) over on https://github.com/mustache/spec

But that doesn't help you with your problem today. For that, something like this might do the trick?

```php
<?php

$arr = [
    'content' => [
        'brand' => [[
            'logo' => [...]
        ]]
    ],
    'relations' => [
        'pages' => [[
            'content' => [...]
        ]]
    ]
];
$arr['@root'] = &$arr;
```

```html+jinja
{{# relations.pages.0 }}
<img src="{{ @root.content.brand.0.logo.source }}" alt="{{ @root.content.brand.0.name }} Logo" />
{{/ relations.pages.0 }}
```

**Comment by designermonkey** [comment]
Now that is a good idea! I'd been looping over all the children and adding the right bits, but that seems quicker, thanks!
