### ISSUE TITLE
Provider for Silex v2

### ISSUE THREAD

**Issue by Rarst** [bobthecow/mustache.php#302]
https://github.com/bobthecow/mustache-silex-provider seems to have issues disabled, so opening one here.

Seems to hard require Silex v1, so doesn't work with v2.

Any plans to update? I could look into changes and possibly PR.

**Comment by bobthecow** [comment]
I don't personally use Silex v2 for anything, so I haven't had a reason to upgrade. If you want to take a shot at it, I'll happily accept PRs :)

**Comment by Rarst** [comment]
Bump! PR open. :)
