### ISSUE TITLE
Change default delimiters

### ISSUE THREAD

**Issue by wrey75** [bobthecow/mustache.php#310]
Hi,

I would like to know if you offer the possibility to change the delimiters _before_ parsing (I mean not in the template).

I checked the `Tokenizer.php` class and I found both `setDelimiters()` and `changeDelimiters()` are private. And, even if the `scan()` method is public, I don't see a way to call it with the second parameter set..

Then, I think the best method is to create my own Tokenizer class and overridding the method "reset" to put my preferred delimiters ("{{" and "}}" are a pain if you plan to add Angular2 code). 

What do you think? Have you a better advice?

**Comment by bobthecow** [comment]
`reset` is private too, and that's getting a bit too deep into the guts of things. Extending Tokenizer and overriding `scan` would probably be the easiest (though I haven't tested so I'm not _positive_ this would work):

```php
public function scan($text, $delimiters = null)
{
    return parent::scan($text, $delimiters ?: '<% %>');
}
```

**Comment by bobthecow** [comment]
A `delimiters` mustache engine option was added in dev branch and will go out in the next release.

**Comment by RichardTMiles** [comment]
Can you please document this better :)
