### ISSUE TITLE
Auto convert Array to comma list?

### ISSUE THREAD

**Issue by mattbryson** [bobthecow/mustache.php#313]
Is there a way to make an `Array` auto `implode` to a string?

````
$my=[
    'nested'=>[
        'data'=>['a','b','c','d']
    ]
];
````

````
The list is {{my.nested.data.array}}
// The list is a,b,c,d
````

At the moment, it throws the usual `'htmlspecialchars() expects parameter 1 to be string, array given`.

This appears to work...

````
'escape' => function($value) {
       $value = is_array($value) ? implode(',', $value) : $value;
        return htmlspecialchars($value, ENT_COMPAT, 'UTF-8');
    },
````

but wondered if there was an existing setting rather than overriding the escape method...

**Comment by bobthecow** [comment]
There's no setting for this, but you could use [the FILTERS pragma](https://github.com/bobthecow/mustache.php/wiki/FILTERS-pragma) and add your own helper:

```php
$m = new Mustache_Engine([
    'pragmas' => [Mustache_Engine::PRAGMA_FILTERS],
]);

$m->addHelper('join', function($value) {
    return implode(',', $value);
});
```

```
The list is {{ my.nested.data | join }}
```

_(Note: I didn't actually run this, but it should be at least mostly correct.)_

**Comment by bobthecow** [comment]
Tested now, and it works. Closing this issue. Feel free to re-open if you need more help :)
