### ISSUE TITLE
Partial inserted in the wrong place

### ISSUE THREAD

**Issue by lcsqlpete** [bobthecow/mustache.php#317]
[EDIT]  For some reason, the second line of the code I'm inserting is not appearing even though I used the Insert Code icon.  It's a div tag with class="container".
[/EDIT]
I have several template files that start with the following code:
{{> top_bar}}
<div class="container">

The top_bar file contains html that creates some elements that appear on the first line of all my web pages.  The code works great in all the files except one.  In that file, the top_bar html appears after the line with the div tag.
I've validated the html in the top_bar file and in the file that invokes it and no errors flagged.  Any ideas why this is happening?

**Comment by lcsqlpete** [comment]
Please ignore. Turned out to be an error on my part.

**Comment by bobthecow** [comment]
👍 glad you got it sorted out.
