### ISSUE TITLE
[ENHANCEMENT] Access to php $_SESSION variables

### ISSUE THREAD

**Issue by lcsqlpete** [bobthecow/mustache.php#318]
I've converted all my web pages to use Mustache, much cleaner.  I've found that I'm often using variables that are loaded with $_SESSION variables which is easy enough to do but might be nice to have a variable that would do it directly.  Perhaps something like {{$ varname}} where varname would be the name of a key within $_SESSION or even a subkey, e.g. user['userid'].

**Comment by nic-d** [comment]
Why not add this yourself using a filter?

**Comment by lcsqlpete** [comment]
I have. The request is a convenience feature so Mustache can access
$_SESSION directly without the the to set a value in the render array.

**Comment by lcsqlpete** [comment]
Sorry, I should have read your reply more closely.  I do not have a filter set up and having read the docs, I'm still not sure how I would do that to access $_SESSION variables.  Could you give me an example please?

**Comment by bobthecow** [comment]
This seems uncommon enough that adding it as a feature to the mustache language itself is probably overkill. You can, however, use [helpers](https://github.com/bobthecow/mustache.php/wiki#helpers) to do something similar, by registering `$_SESSION` (or variables inside) on the engine itself:

```php
$mustache = new Mustache_Engine(array(
    'helpers' => array('_SESSION' => $_SESSION),
));
```

These can then be used in your templates:

```html+mustache
{{_SESSION.user.userid}}
```

**Comment by lcsqlpete** [comment]
Thanks Justin, that's a good solution.

**Comment by bobthecow** [comment]
No problem!
