### ISSUE TITLE
accessing variables directly in template

### ISSUE THREAD

**Issue by saiballo** [bobthecow/mustache.php#321]
Hi all,

Is it possible to access php variables in mustache template?

for example in my page.php I have

$name = 'myvalue';

and I want to access it in template with something like this:

{{name}}

without passing it like:

echo $m->render($template, $name);

**Comment by bobthecow** [comment]
No, this isn't generally supported. If `$name` is a global, there are shenanigans you can pull, but Mustache really expects you to pass in the context you need to render.

You could do one of these, though:

```php
echo $m->render($template, get_defined_vars());
echo $m->render($template, compact('name'));
```
