### ISSUE TITLE
Nested Arrays (PHP)

### ISSUE THREAD

**Issue by lcsqlpete** [bobthecow/mustache.php#323]
I'm trying to figure out how to iterate thought a nested array structure of this form with the array variable named Messages:

`[0]
   [MessageKeyword]=> ABC
   [Application]=> WEB 
   [Translations]
      [0]
         [Language]=>English
         [Text]=>Hello
      [1]
         [Language]=>French
         [Text] => Bonjour
[1]
   [MessageKeyword]=> DEF
   [Application]=> WEB
      [Translations]
          [0]
            [Language]=>English
            [Text]=>Goodbye
          [1]
            [Language] => French
            [Text]=> Au Revoirs
`

I tried referring to it in my template as

{{#Messages}}
   <references to {MessageKeyword}} and {{Application}}>
   {{#Messages.Translations}}
      <references to {{Language}} and {{Text}}
   {{/Messages.Translations}}
{{/Messages}}

I'm getting a runtime exception "Uncaught exception 'Mustache_Exception_SyntaxException' with message 'Nesting error: Messages (on line 430) vs. Messages.Translations (on line 451)'

I also tried it by referring to {{#Translations} instead of {{#Messages.Translations}} and got a similar error message. 

Is it possible to do this?

Apologies for the formatting of the array, can't seem to get carriage returns into it.

**Comment by bobthecow** [comment]
I'm having a hard time following this because of the formatting. You can get it to format as a block by using "fenced code blocks". Add three backticks (`\``) on their own line at the start and end of your array and template :)

**Comment by lcsqlpete** [comment]
Thanks for the three backticks hint. I've been using the <> icon to insert code which only inserts one backtick so trying again here with three of them and more complete information.

Here's an example of the array I pass to Mustache.

```
[Translations] => Array
        (
            [0] => Array
                (
                    [MessageKeyword] => HELLO
                    [Application] => MOBILE
                    [Messages] => Array
                        (
                            [0] => Array
                                (
                                    [LanguageName] => English (US)
                                    [MessageText] => Hello
                                )

                            [1] => Array
                                (
                                    [LanguageName] => French
                                    [MessageText] => Bonjour 
                                )

                        )

                )

            [1] => Array
                (
                    [MessageKeyword] => GOODBYE
                    [Application] => MOBILE
                    [Messages] => Array
                        (
                            [0] => Array
                                (
                                    [LanguageName] => English (US)
                                    [MessageText] => Goodbye
                                )

                            [1] => Array
                                (
                                    [LanguageName] => French
                                    [MessageText] => Au Revoir 
                                )

                        )

                )
```

Here's a snippet of the html code.

```
<table id="tableSearchResults" class="table table-hover  table-striped table-condensed">
                        <thead>
                            <tr>
                                <th>Keyword</th>
                                <th>Application</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {{# Translations}}
                            <tr class="accordion-toggle collapsible-row" data-toggle="collapse" data-parent="#OrderPackages" data-target=".packageDetails{{MessageID}}">
                                <td>{{MessageKeyword}}</td>
                                <td>{{Application}}</td>
                                <td><i class="indicator glyphicon glyphicon-chevron-up pull-right"></i>

                                </td>
                            </tr>
                            {# Translations.Messages}}
                            <tr>
                                <td colspan="3" class="hiddenRow">
                                    <div class="accordion-body collapse packageDetails{{tdata.MessageID}}" id="accordion1">
                                        <table>
                                            <tr>
                                                <td>{{LanguageName}}</td>
                                                <td>{{MessageText}}</td>
                                            </tr>
                                        </table>
                                    </div>
                                </td>
                            </tr>
                            {{/ Translations.Messages}}
                            {{/ Translations}}
                        </tbody>
                    </table>
```
The table code is from  an example I found online for a Bootstrap 3 table with collapsible rows.  In this case, the Translations outer array would form the rows which can be expanded/collapsed (showing the Keyword and Application) and the Messages subarray would be the rows that would be shown/hidden under each of the main rows.

As a reminder, the error message is  "Uncaught exception 'Mustache_Exception_SyntaxException' with message 'Nesting error: Messages (on line 430) vs. Messages.Translations (on line 451)'".  I also tried it with just {{Messages}} instead of {{Translations.Messages}} and got the same error. 

Thanks,
Pete

**Comment by lcsqlpete** [comment]
I think I found the problem.  There;'s a missing { before Translations.Messages.  I use Netbeans and for some reason, it seems reluctant to insert a second { char in some circumstances.

Anyway, sorry for the misunderstanding, thinkI'm back on track.

**Comment by bobthecow** [comment]
No worries. Glad you could track it down.
