### ISSUE TITLE
Able to add Helpers to String 

### ISSUE THREAD

**Issue by Sysix** [bobthecow/mustache.php#326]
Hello Guys,

I have a a "Feature" Request.
I have a Mustache Template for a Submittion-Success Message.

This Message should be translated. I added a Helper for that (note I use WP):

```
    public function __construct(array $options = array())
    {
        parent::__construct($options);

        $this->addHelper('__', function ($val) {
            return __($val, 'name');
        });
```

Now I want to set the message in my mustache template and translate it via my helper function.
But How?

I tried `{{ "form was not found" | __ }}`, but it failed without an error.

**Comment by Sysix** [comment]
Ups.. sorry I did not search right in the Tickets.

A good example I found here:
https://github.com/bobthecow/mustache.php/tree/a3f6d55996dd28b58f3a909d474189a3c1aa693f/test/fixtures/examples/i18n

**Comment by bobthecow** [comment]
:) glad you got it sorted out!
