### ISSUE TITLE
Rendering same template different context??

### ISSUE THREAD

**Issue by thepurpleblob** [bobthecow/mustache.php#332]
I have two objects (say $a and $b). They have the same fields but different data. 

I want to display the same 'chunk' of template first with the data in $a and then with the data in $b.

Is there some way to do this - say with a partial? I don't really want to build these into an array (although I will if that's the only way).

**Comment by thepurpleblob** [comment]
Never mind... having drunk more coffee and slept on it I have concluded that this is a pretty stupid question :-D

**Comment by bobthecow** [comment]
:)
