### ISSUE TITLE
Variable = 0?

### ISSUE THREAD

**Issue by jbostoen** [bobthecow/mustache.php#334]
Hi

I currently use an IF block to see if a value's been determined. But in some cases, a distance is determined, but is simply 0. It's hidden. 

How can I make sure Mustache displays this variable when it equals 0? I tried casting it explicitly as a string before passing it, but that doesn't work either. 

What's the work around or where could I look to accept a variable which is 0?

---

Is the following chance acceptable? (haven't created a pull request)
It adds  || $value == "0"
(empty value = 0, so comparing it to string)

```
 private function section%s(Mustache_Context $context, $indent, $value)
        {
            $buffer = \'\';

            if (%s) {
                $source = %s;
                $result = call_user_func($value, $source, %s);
                if (strpos($result, \'{{\') === false) {
                    $buffer .= $result;
                } else {
                    $buffer .= $this->mustache
                        ->loadLambda((string) $result%s)
                        ->renderInternal($context);
                }
            } elseif (!empty($value) || $value == "0" ) {
                $values = $this->isIterable($value) ? $value : array($value);
                foreach ($values as $value) {
                    $context->push($value);
                    %s
                    $context->pop();
                }
            }

            return $buffer;
        }
```

**Comment by thepurpleblob** [comment]
Set a flag for valid values and pass that to mustache? Anything that doesn't fit in with moustache's very narrow logic has to be done in the PHP logic.
