### ISSUE TITLE
Cache security

### ISSUE THREAD

**Issue by thepurpleblob** [bobthecow/mustache.php#335]
What are the minimum access requirements for the moustache cache?

Files are currently created as 0644, which seems fine but I have had problems in the past with PHP worms getting into cache files (this was with Twig, but I assume the principal is the same) due to PHP files being writeable. 

Sorry - I know this a ramble but I am uncomfortable with having writeable PHP files on my server (even/especially by the web server user) and I wondered what your thoughts are regarding best practice.

**Comment by bobthecow** [comment]
Unfortunately, if Mustache has permissions to write to the cache, other PHP code running under the same process will as well. Ultimately, once you've got arbitrary code execution you've got arbitrary code execution, so I'd suggest preventing that :)

If you want one more layer of defense, and your templates are somewhat predictable, you could pre-warm the template cache at build/deploy time and change permissions to read-only. Then at runtime you wouldn't be able to write the directory.
