### ISSUE TITLE
How to use user defined function in mustache php

### ISSUE THREAD

**Issue by abhishekthakur1995** [bobthecow/mustache.php#338]
I have set up `mustache php` in my project.

    echo $template->render(array(
         'data'=>$data, 
         'lang'=>$lang,
         'getMaritialStatus' => function($text, Mustache_LambdaHelper $helper) {
           return Common::getTextInHindi(ucwords(strtolower($helper->render($text))));
          }
    ));

and my user defined function is 

    public static function getTextInHindi($maritialStatus) {
          return $GLOBALS['lang'][$maritialStatus];
    }

Now in my user defined function as you can see above when I try to print 

    print_r($GLOBALS['lang']['Married']);  //gives correct output
    print_r($GLOBALS['lang'][$maritialStatus]); //gives undefined index error

even though `$maritialStatus` contains the string `'Married'`.

Why is this happening

**Comment by mxdpeep** [comment]
*MARITAL*<<< not MARITIAL


s pozdravem,

*Filip Oščádal*
