### ISSUE TITLE
Getting whole template before rendering

### ISSUE THREAD

**Issue by kweensey** [bobthecow/mustache.php#342]
Hello,

Is there a way to get composed template from partials before actual rendering? I need this so I can parse the template and load suitable data (there are parameters for loading in template).

Thank you for your amazing work!

**Comment by bobthecow** [comment]
No. It doesn’t compose the template before rendering. Partials are lazily loaded at runtime, to avoid doing work if they’re not needed, so there’s never a “whole template”.

**Comment by kweensey** [comment]
Okay, that's what I was worried about. Thanks for very quick answer!
