### ISSUE TITLE
Possible to allow loader to load all including in subdirectories? 

### ISSUE THREAD

**Issue by Rhyspacker** [bobthecow/mustache.php#345]
Hi,

I was wondering if it's possible for the mustache loader to load any files in a templates directory instead of having to define exactly which folders. With Gulp/Webpack Handlebars setups it simply finds all .hbs files and gives access to them. 

This kind of behaviour is what I'm thinking with '*': 
return new Mustache_Engine(array(
   'loader' => new Mustache_Loader_FilesystemLoader(get_template_directory() . '/components/&#42;')

This isn't really an issue but I thought it could be a neat feature if it's possible with php.

Cheers.

**Comment by bobthecow** [comment]
You could absolutely make your own loader. They're pretty straightforward :)
