### ISSUE TITLE
Iterate associative array

### ISSUE THREAD

**Issue by devgutt** [bobthecow/mustache.php#346]
To reopen this issue #197 about iterate associative array. 

Sorry to reopen an old thread, but this is a problem I am facing right now, and I think the solution that you proposed is not ideal. if I can iterate on a list, I should be able to iterate on a hash array either. Semantically, I think it would be correct to use:

```
 {{# hash_array }}
    {{# . }}
        <p> {{ key }} : {{ value }} </p>
    {{/ . }}
 {{/ hash_array }}
```

**Comment by Chemaclass** [comment]
what exactly is `hash_array`?

**Comment by devgutt** [comment]
It would be an associative array in PHP.

**Comment by bobthecow** [comment]
Your example there would be syntactically ambiguous.

For better or for worse, Mustache decided to use the same symbol for "iterate" as well as "use this object for context", and we need _something_ to decide which it is — especially in PHP, where we use the same primitive for both.

If my example before doesn't do it for you, another answer is to use the `filters` pragma to force an associative array to be iterable:

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

$m = new Mustache_Engine([
  'pragmas' => [Mustache_Engine::PRAGMA_FILTERS],
  'helpers' => [
    'as_key_value' => function ($array) {
        $res = [];
        foreach ($array as $key => $value) {
            $res[] = ['key' => $key, 'value' => $value];
        }
        return $res;
    }
  ],
]);

$tpl = <<<EOS
{{# hash_array | as_key_value }}
  <p>{{ key }}: {{ value }}</p>
{{/ hash_array }}
EOS;

$data = [
  'hash_array' => [
    'foo' => 'one',
    'bar' => 'two',
    'baz' => 'three',
  ],
];

echo $m->render($tpl, $data);
```

... which results in:

```html
<p>foo: one</p>
<p>bar: two</p>
<p>baz: three</p>
```
