### ISSUE TITLE
Notice on PHP 7.4

### ISSUE THREAD

**Issue by Meryl** [bobthecow/mustache.php#348]
On PHP 7.4 Mustache generates a "Trying to access array offset on value of type null" notice on line 278 of Parser.php, due to checking an array offset on a null-object. Solution: Check if $parent is not null or cast to array.

**Comment by tomjn** [comment]
I tried to create a PR to fix this in https://github.com/bobthecow/mustache.php/pull/349

**Comment by bobthecow** [comment]
This is fixed in v2.13.0 :)
