### ISSUE TITLE
Possibly Insecure default option

### ISSUE THREAD

**Issue by Kirill89** [bobthecow/mustache.php#353]
Hey,

I think [entity_flags option](https://github.com/bobthecow/mustache.php/wiki#entity_flags) should be `ENT_QUOTES` by default.

Or maybe worth to mention this option in examples or in other visible places.

Otherwise it could lead to XSS in cases like:

```php
$m = new Mustache_Engine;
echo $m->render("<a href='/user/{{id}}'>{{name}}</a>", array(
    'name' => 'User',
    'id' => "1' onmouseover='alert(1)",
));
```

WDYT?

**Comment by bobthecow** [comment]
Changing the default would be a backwards compatibility break, so we can consider it for the next major release. Until then, updating documentation and examples would be a great idea.
