### ISSUE TITLE
Calling getLogger and setLogger on a type hinted as Mustache_Cache

### ISSUE THREAD

**Issue by quasilyte** [bobthecow/mustache.php#358]
Mustache_Cache contains only 2 methods: load and cache.

In a few places we call getLogger and setLogger on a value that is type hinted as Mustache_Cache:
```
call to undefined method {\Mustache_Cache}->getLogger() at mustache.php/src/Mustache/Engine.php:459
call to undefined method {\Mustache_Cache}->setLogger() at mustache.php/src/Mustache/Engine.php:460
call to undefined method {\Mustache_Cache}->getLogger() at mustache.php/src/Mustache/Engine.php:561
call to undefined method {\Mustache_Cache}->setLogger() at mustache.php/src/Mustache/Engine.php:562
```
If adding getLogger and setLogger to a Mustache_Cache interface is not an option, maybe it's possible to use Mustache_Cache_AbstractCache as a type hint?

**Comment by bobthecow** [comment]
Thank you! That should have been in the interface. It'll be updated in the next release.
