### ISSUE TITLE
PHP 7.4 - Trying to access array offset on value of type null in /home/xxx/public_html/Mustache/Parser.php on line 278

### ISSUE THREAD

**Issue by Raf-sns** [bobthecow/mustache.php#359]
Hi !
i see this error on my logs during a migration to a 7.4 PHP server (from 5.6 PHP) : 
"Trying to access array offset on value of type null in /home/xxxx/public_html/Mustache/Parser.php on line 278"

I not be able to Pull, fix this on Parser.php line 278 : 
Replace : 
`private function checkIfTokenIsAllowedInParent($parent, array $token)
    {
        if ($parent[Mustache_Tokenizer::TYPE] === Mustache_Tokenizer::T_PARENT) {
            throw new Mustache_Exception_SyntaxException('Illegal content in < parent tag', $token);
        }
    }`
By : ( Watch the isset() for the $parent array )
`private function checkIfTokenIsAllowedInParent($parent, array $token)
    {
        if (isset($parent[Mustache_Tokenizer::TYPE]) === Mustache_Tokenizer::T_PARENT) {
            throw new Mustache_Exception_SyntaxException('Illegal content in < parent tag', $token);
        }
    }`
I think this must be modified in source code for not throw an exeption in PHP 7.4
Hope to help - Love Mustache !!
Raf

**Comment by bobthecow** [comment]
This is fixed in v2.13.0. Please upgrade!

https://github.com/bobthecow/mustache.php/releases/tag/v2.13.0
