### ISSUE TITLE
Lambdas are defined differently than on mustache.github.io

### ISSUE THREAD

**Issue by vshih** [bobthecow/mustache.php#360]
https://github.com/bobthecow/mustache.php/wiki/Mustache-Tags indicates that Lambdas are defined directly as data values, e.g. `$data['embiggened']`:
```php
<?php
array(
  'name' => "Willy",
  'embiggened' => function($text, Mustache_LambdaHelper $helper) {
    return strtoupper($helper->render($text));
  }
);
```

But according to [mustache.github.io](https://github.com/mustache/mustache.github.com/blob/a0fcda1b6d4efacc78e32235212a1730c3a09e9a/mustache.5.html#L261) the value is a callback that returns the Lambda:

```javascript
Hash:
{
  "name": "Willy",
  "wrapped": function() {
    return function(text, render) {
      return "<b>" + render(text) + "</b>"
    }
  }
}
```

Is this intentional?

**Comment by bobthecow** [comment]
Yes, it's intentional, and yes, the PHP implementation follows the mustache spec.

>When the value is a callable object, such as a function or lambda, the object will be invoked and passed the block of text.

The value in your first example _is_ callable: `is_callable($data['embiggened']) === true`
