### ISSUE TITLE
Implement an option that cleans up html comments

### ISSUE THREAD

**Issue by Raf-sns** [bobthecow/mustache.php#364]
Hi, 
Sorry for the translation of my title, this is only a food for thought ...

in order to clean my html code of its output comments I added the following code in: Mustache / Loader / FilesystemLoader.php / -> protected function loadFile ($ name):

```
 /**
     * Helper function for loading a Mustache file by name.
     *
     * @throws Mustache_Exception_UnknownTemplateException If a template file is not found
     *
     * @param string $name
     *
     * @return string Mustache Template source
     */
    protected function loadFile($name)
    {
        $fileName = $this->getFileName($name);

        if ($this->shouldCheckPath() && !file_exists($fileName)) {
            throw new Mustache_Exception_UnknownTemplateException($name);
        }

        // original return version
        // return file_get_contents($fileName);

        // modified version
        $templ = file_get_contents($fileName);

        // CLEAN / UN-ClEAN  -> UN-COMMENT following lines TO CLEAN
        //                   -> COMMENT for not to clean (preserve comments)
        $templ = trim($templ); // trim
        $templ = preg_replace('#[ ]{2,}#s', ' ', $templ); // all white spaces
        $templ = preg_replace('#<!--.*?-->#s', '', $templ); // all comments
        $templ = preg_replace('#\s|\r\n#s', ' ', $templ); // all

        return $templ;
        // modified version

    }
```

I think there is a cleaner way to do this but I am having trouble implementing it, it would be nice to have it as an option, like for template extensions we could have:

```
// array() of datas
$ARR_datas = array('hello' => 'hello world !');

// options with clean_html -> boolean ? as an option
$options = array('extension' => '.html',  'clean_html' => true);

$m = new Mustache_Engine(array(
 'loader' => new Mustache_Loader_FilesystemLoader(dirname(__DIR__) . '/templates', $options)
));

echo $m->render('home', $ARR_datas);

```
This render the template without html comments, you can keep them 
for dev. and they will not be rendered in output -> it is also a way to reduce the code, and save the planet   ^_^

**Comment by bobthecow** [comment]
There are plenty of libraries to do this exact thing. I feel like they're outside the scope of a templating library.

Your eventual solution should be composed of a bunch of smaller libraries that do a small number of things well, not one massive thing that tries to be everything to everyone :)
