### ISSUE TITLE
PHP 8 warns of a typo in `sprintf` in `getTemplateClassName()` - `%i`

### ISSUE THREAD

**Issue by oppiansteve** [bobthecow/mustache.php#366]
`ValueError: Unknown format specifier "i" in mustache.php:237`

```
public function getTemplateClassName($source)
    {
        return $this->templateClassPrefix . md5(sprintf(
            'version:%s,escape:%s,entity_flags:%i,charset:%s,strict_callables:%s,source:%s',
            self::VERSION,
            isset($this->escape) ? 'custom' : 'default',
            $this->entityFlags,
            $this->charset,
            $this->strictCallables ? 'true' : 'false',
            $source
        ));
    }
```

`%i` isn't an allowed specifier perhaps `%d` was intended?

**Comment by bobthecow** [comment]
Yep! That should be `%d`. Thanks PHP 8 🙂

**Comment by bobthecow** [comment]
Sorry, I meant to come back to this and comment on it, and completely forgot. 

The version of `getTemplateClassName` you're using here is 4+ years old. More recent versions don't have this issue. I'd suggest updating!
