### ISSUE TITLE
Template inheritance not working

### ISSUE THREAD

**Issue by columbbus** [bobthecow/mustache.php#367]
I am trying to get template inheritance to work with mustache.php. I've found several sources, which state that this feature is available in mustache.php:

- https://github.com/bobthecow/mustache.php/issues/172
- https://github.com/mustache/spec/pull/75

However I could not get this to work. I tried a simple example using the templates (mypage.mustache, base.mustache and header.mustache) described in here: https://github.com/mustache/spec/pull/75

Templates:
```
{{! header.mustache }}
<head>
  <title>{{$title}}Default title{{/title}}</title>
</head>
```
```
{{! base.mustache }}
<html>
  {{$header}}{{/header}}
  {{$content}}{{/content}}
</html>
```
```
{{! mypage.mustache }}
{{<base}}
  {{$header}}
    {{<header}}
      {{$title}}My page title{{/title}}
    {{/header}}
  {{/header}}

  {{$content}}
    <h1>Hello world</h1>
  {{/content}}
{{/base}}
```

Main script:

```
<?php

require __DIR__ . '/vendor/autoload.php';


$m = new Mustache_Engine([
    'loader' => new Mustache_Loader_FilesystemLoader(dirname(__FILE__)),
]);
$template = $m->loadTemplate('mypage.mustache');
$output = $template->render([]);

echo $output;
```

File structure:
```
|- vendor/
|- base.mustache
|- compose.json
|- header.mustache
|- main.php
|- mypage.mustache
```

But when I run the script, I get the following error:
```
PHP Fatal error:  Uncaught Mustache_Exception_SyntaxException: Illegal content in < parent tag in /Users/pascal/Desktop/demo/vendor/mustache/mustache/src/Mustache/Parser.php:279
Stack trace:
#0 /Users/pascal/Desktop/demo/vendor/mustache/mustache/src/Mustache/Parser.php(145): Mustache_Parser->checkIfTokenIsAllowedInParent(Array, Array)
#1 /Users/pascal/Desktop/demo/vendor/mustache/mustache/src/Mustache/Parser.php(146): Mustache_Parser->buildTree(Array, Array)
#2 /Users/pascal/Desktop/demo/vendor/mustache/mustache/src/Mustache/Parser.php(43): Mustache_Parser->buildTree(Array)
#3 /Users/pascal/Desktop/demo/vendor/mustache/mustache/src/Mustache/Engine.php(783): Mustache_Parser->parse(Array)
#4 /Users/pascal/Desktop/demo/vendor/mustache/mustache/src/Mustache/Engine.php(808): Mustache_Engine->parse('{{! mypage.must...')
#5 /Users/pascal/Desktop/demo/vendor/mustache/mustache/src/Mustache/Engine.php(738): Mustache_Engine->compile('{{! mypage.must...')
#6 /Users/pascal/Desktop/demo/vendor/mustache/mustache/src/Mustache/Engine.php(657): in /Users/pascal/Desktop/demo/vendor/mustache/mustache/src/Mustache/Parser.php on line 279
```

**Comment by bobthecow** [comment]
Because it's a non-standard extension to the spec, it's disabled by default. You can enable it with the `BLOCKS` pragma: https://github.com/bobthecow/mustache.php/wiki/BLOCKS-pragma

**Comment by columbbus** [comment]
I thought I've searched the whole documentation, I didn't see that. I'm sorry, I guess I got a little bit confused, because everyone is calling this feature differently (template inheritance, partial overrides, blocks, ...).

I've tried the example given on the doc page you've linked and I can run it without errors now. However the overriding doesn't seem to work for me. The title is still 'My Awesome Title' instead of 'How to do x, y and z'.

Do you happen to where my fault is?

**Comment by bobthecow** [comment]
It's hard to see without your exact code, but here's a full working example:

https://gist.github.com/bobthecow/3b4f668b4a962569747004f9f3a0f72c

You should be able to clone or download, `composer install` then run it with `php ./test.php` and verify the output.

**Comment by columbbus** [comment]
Great thank you very much. It works now!
