### ISSUE TITLE
How to escape {{ }}

### ISSUE THREAD

**Issue by thepurpleblob** [bobthecow/mustache.php#372]
Is there some way of passing through the curly braces literally?  I'm using mustache in conjunction with Vue which also uses the mustache syntax so I'd like to selectively pass them through unprocessed.

**Comment by thepurpleblob** [comment]
Actually.... I immediately realised that I can simply change the delimiters in Vue. But it still might be interesting to know if there's a way

**Comment by bobthecow** [comment]
There is not. The standard approach is to change delimiters.

**Comment by Fabacks** [comment]
I also use mustache php and mustache js
To ignore the code and leave it to js I use : {{=<% %>=}} my code ignored <%={{ }}=%>
