### ISSUE TITLE
Loading a partial programmatically

### ISSUE THREAD

**Issue by lcsqlpete** [bobthecow/mustache.php#379]
I feel like I'm missing something obvious but I have a need to render a mustache partial directly from my code not by referencing it in a main template

Right now, I have a main template that just loads the partial, e.g. main template name is my_template_main, contents {{>my_template}}, but seems like there must be a better way of doing it.

Here's how I initialise Mustache:

    public function __construct()
    {
        session_start();
        require_once $_SERVER["DOCUMENT_ROOT"] . '/Mustache/Autoloader.php';
        Mustache_Autoloader::register();
        $this->mustache = new Mustache_Engine(
            array(
                'loader' => new Mustache_Loader_FilesystemLoader(__DIR__ . '/templates'),
                'partials_loader' => new Mustache_Loader_FilesystemLoader(__DIR__ . '/templates/partials'),
                'helpers' => array('_SESSION' => $_SESSION),
            )
        );
  
I guess I'm looking for a way to call the partials_loader directly.

**Comment by bobthecow** [comment]
From your setup you should be able to get it by rendering `partial/$template`, right?

**Comment by lcsqlpete** [comment]
Thak yo Bob, that works.  I knew I was missing something obvious!
