### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by mxhCodes** [bobthecow/mustache.php#381]
Sorry to post an issue that is not an issue. But I wanted to say thank you on this way, your library is awesome!

I've built an integration for the Drupal CMS (https://www.drupal.org/project/mustache_templates). That integration allows to write Mustache templates both for server-side rendering with Mustache.php as well as on the client side with Mustache.js. Enjoy 😊

**Comment by bobthecow** [comment]
Thanks so much :)
