### ISSUE TITLE
PHP 8.1 DEPRECATED warning

### ISSUE THREAD

**Issue by scr4bble** [bobthecow/mustache.php#382]
Getting this error:
`PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /paxflow/templatesc/__Mustache_a68c6535586958218adc11f5a8c39526.php on line 101`

Out of this compiled Mustache template:
```
    94	    private function section482a043a1d6af238da886e687193f8a1(Mustache_Context $context, $indent, $value)
    95	    {
    96	        $buffer = '';
    97	    
    98	        if (!is_string($value) && is_callable($value)) {
    99	            $source = 'dd_right';
   100	            $result = call_user_func($value, $source, $this->lambdaHelper);
   101	            if (strpos($result, '{{') === false) {      <--------------------------- here

```

Template snippet:
```
{{$ navbar-navigation-right-default }}
	{{#set_flag}}dd_right{{/set_flag}}    <-------------------- here
	{{# navbar_right_links }}
		{{> app.snippet.menuitem }}
	{{/ navbar_right_links }}
{{/ navbar-navigation-right-default }}
```

Engine helper definition:
```
$engine->addHelper('set_flag', function($val) {
	$GLOBALS['mustache_current_flags'][$val] = true;
});
```

Is this something that Mustache should be able to handle?

**Comment by scr4bble** [comment]
So the warning disappears when an empty string is returned from the function provided in addHelper() instead of null.
I guess Mustache should take care of this instead of the user.
```
$engine->addHelper('set_flag', function($val) {
	$GLOBALS['mustache_current_flags'][$val] = true;
	return "";
});
```

**Comment by bobthecow** [comment]
Great, thanks for reporting this! It's been fixed and will go out with the next release.
