### ISSUE TITLE
PHP 8.0 compatibility - deprecated warnings

### ISSUE THREAD

**Issue by jms212004** [bobthecow/mustache.php#385]
Hi,
when i scan with 
 phpcs -p . --standard=PHPCompatibility --runtime-set testVersion 8.0 --extensions=php

Return:
FILE: mustache/Mustache/Tokenizer.php
--------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------
 102 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2 and removed since PHP 8.0
--------------------------------------------------------------------------------------------------------------

Best regard

**Comment by bobthecow** [comment]
Thanks for reporting! The check has to stay (because Mustache works with versions of PHP that still support it) but the whole thing is wrapped in a check for `< PHP 8.0` now, so eventually it'll be completely removed :)
