### ISSUE TITLE
htmlspecialchars() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by brijesh6491** [bobthecow/mustache.php#386]
ErrorException: htmlspecialchars() expects parameter 1 to be string, array given in /var/www/project/vendor/mustache/mustache/src/Mustache/Cache/NoopCache.php(45) : eval()'d code:44
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'htmlspecialchar...', '/var/www/gym-ma...', 44, Array)
#1 /var/www/project/vendor/mustache/mustache/src/Mustache/Cache/NoopCache.php(45) : eval()'d code(44): htmlspecialchars(Array, 2, 'UTF-8')
#2 /var/www/project/vendor/mustache/mustache/src/Mustache/Template.php(67): __Mustache_c0e29dada346c14e3c7cc23796b2393f->renderInternal(Object(Mustache_Context))
#3 /var/www/project/vendor/mustache/mustache/src/Mustache/Engine.php(236): Mustache_Template->render(Array)
#4 /var/www/project/app/Notifications/PromotionEmailNotification.php(45): Mustache_Engine->render('<p>Bonjour {{na...', Array)
    #5 /var/www/project/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(50): App\Notifications\PromotionEmailNotification->toMail(Object(Illuminate\Notifications\AnonymousNotifiable))
    #6 /var/www/project/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(127): Illuminate\Notifications\Channels\MailChannel->send(Object(Illuminate\Notifications\AnonymousNotifiable), Object(App\Notifications\PromotionEmailNotification))
    #7 /var/www/project/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(102): Illuminate\Notifications\NotificationSender->sendToNotifiable(Object(Illuminate\Notifications\AnonymousNotifiable), '4fcb56ae-d314-4...', Object(App\Notifications\PromotionEmailNotification), 'mail')
    #8 /var/www/project/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\Notifications\NotificationSender->Illuminate\Notifications\{closure}()
    #9 /var/www/project/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(104): Illuminate\Notifications\NotificationSender->withLocale(NULL, Object(Closure))
    #10 /var/www/project/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(76): Illuminate\Notifications\NotificationSender->sendNow(Array, Object(App\Notifications\PromotionEmailNotification))
    #11 /var/www/project/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(42): Illuminate\Notifications\NotificationSender->send(Array, Object(App\Notifications\PromotionEmailNotification))
    #12 /var/www/project/vendor/laravel/framework/src/Illuminate/Notifications/AnonymousNotifiable.php(38): Illuminate\Notifications\ChannelManager->send(Object(Illuminate\Notifications\AnonymousNotifiable), Object(App\Notifications\PromotionEmailNotification))
    #13 /var/www/project/app/Jobs/PromotionEmailJob.php(37): Illuminate\Notifications\AnonymousNotifiable->notify(Object(App\Notifications\PromotionEmailNotification))
    #14 [internal function]: App\Jobs\PromotionEmailJob->handle()
    #15 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
    #16 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
    #17 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
    #18 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
    #19 /var/www/project/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
    #20 /var/www/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\PromotionEmailJob))
    #21 /var/www/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\PromotionEmailJob))
    #22 /var/www/project/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
    #23 /var/www/project/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\PromotionEmailJob), false)
    #24 /var/www/project/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
    #25 /var/www/project/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(324): Illuminate\Queue\Jobs\Job->fire()
    #26 /var/www/project/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(274): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
    #27 /var/www/project/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions))
    #28 /var/www/project/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions))
    #29 /var/www/project/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
    #30 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
    #31 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
    #32 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
    #33 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
    #34 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
    #35 /var/www/project/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
    #36 /var/www/project/vendor/symfony/console/Command/Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
    #37 /var/www/project/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
    #38 /var/www/project/vendor/symfony/console/Application.php(886): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #39 /var/www/project/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #40 /var/www/project/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #41 /var/www/project/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #42 /var/www/project/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #43 /var/www/project/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #44 {main}

**Comment by bobthecow** [comment]
It's because you're trying to treat an array like a string. If we force a cast to `(string)` you'll still get a warning (this time about an Array to string conversion) _and_ you'll get the literal string `Array` where you'd otherwise have nothing.

This seems strictly worse.

**Comment by brijesh6491** [comment]
> It's because you're trying to treat an array like a string. If we force a cast to `(string)` you'll still get a warning (this time about an Array to string conversion) _and_ you'll get the literal string `Array` where you'd otherwise have nothing.
> 
> This seems strictly worse.

sorry my bad i resolved this issue is from my side when i debug i got it issue

**Comment by bobthecow** [comment]
No worries, glad you got it resolved!
