### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by altm4n** [bobthecow/mustache.php#388]
In Mustache.php v2.14.0 and before, Sections tag can lead to arbitrary php code execution when section value is controllable.

**Comment by bobthecow** [comment]
Are you referring to this? https://github.com/bobthecow/mustache.php/wiki/Callable

**Comment by altm4n** [comment]
No,This attack is also work even if&nbsp;strict_callables is true.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bobthecow/mustache.php"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月19日(星期三) 中午11:35
***@***.***&gt;;
抄送:&nbsp;"    ***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [bobthecow/mustache.php] Security Issue (Issue #388)





 
Are you referring to this? https://github.com/bobthecow/mustache.php/wiki/Callable
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
