### ISSUE TITLE
Assign var

### ISSUE THREAD

**Issue by Pok4** [bobthecow/mustache.php#392]
Does the new Version Support assign var to pass multiple definitions in it? If not can you give me the example how to do that?

**Comment by bobthecow** [comment]
I don't think I understand what you're looking for. Can you share an example of what you've tried?

**Comment by Pok4** [comment]
Hi, bob! The assign var is a array with pre-defined template variables. This is popular in Smarty template engine.

I have a working variant but is working only in old version (i don't know the last version is capable to use this one).

Here is:
```
//global template variables
$mustache->assign([
	'username'=>$bb_username,
	'is_logged'=>$bb_is_anonymous ? false : true,
	'baseurl'=>url(),
	'form_token'=> $token,
]);

```
Now in template i can use this variables within {{}}.

I don't need another code to use this variables, only this one.

I can copy a my modification on older version.. The version is 2.10 if i remember well...
Engine.php, line 244:
```
    public function render($template, $context = array())
    {
        //pok4 edit
 
        return $this->loadTemplate($template)->render($context);
    }
```

Line ~208 / Engine.php
```
        public function assign($key,$val=""){
        
        if(is_string($key))
            $this->assigned[$key] = $val;
        
        if(is_array($key))
            $this->assigned = array_merge_recursive($this->assigned,$key);
        
        return
            $this;
    }
```

Line ~ 60 / Engine.php
```
    //pok4 edit
    public $assigned = array();
```

Line ~60 / Template.php

```
    public function render($context = array())
    {
        return $this->renderInternal(
            $this->prepareContextStack(array_merge($context,$this->mustache->assigned))
        );
    }
```

This is very nice feature and i have cms system wich is working with this one... I need this in last version.
Thank you in advance!

**Comment by Pok4** [comment]
oh, i forget this too:

    public function unassign($key){
        if(is_string($key) && isset($this->assigned[$key]))
            unset($this->assigned[$key]);            
        return 
            $this;
    }

**Comment by bobthecow** [comment]
Global variables isn't a pattern I want to add to Mustache, but it would be really easy to do this yourself (and do it without needing to patch the engine every time):

```php
class MyMustache extends Mustache_Engine {
  public $assigned = [];

  public function assign($key, $val = null) {
    if (is_string($key)) {
      $this->assigned[$key] = $val;
    }

    if (is_array($key)) {
      $this->assigned = array_merge_recursive($this->assigned, $key);
    }

    return $this;
  }

  public function unassign($key) {
    if (is_string($key) && isset($this->assigned[$key])) {
      unset($this->assigned[$key]);
    }

    return $this;
  }

  public function loadTemplate($name) {
    return new MyMustacheTemplate($this, parent::loadTemplate($name));
  }
}

class MyMustacheTemplate extends Mustache_Template {
  protected $template;

  public function __construct(Mustache_Engine $engine, Mustache_Template $template) {
    parent::__construct($engine);
    $this->template = $template;
  }

  public function render($context = []) {
    return $this->template->render(array_merge($this->mustache->assigned, $context));
  }

  public function renderInternal(Mustache_Context $context, $indent = '') {
    return $this->template->renderInternal($context, $indent);
  }
}
```

Use this, rather than using `Mustache_Engine` directly:

```php
<?php

$m = new MyMustache();
$m->assign([
  'username' => 'bobthecow',
  'is_logged' => false,
]);

$tpl = <<<EOS
{{# is_logged }}
{{ greeting }}, {{ username }}.
{{/ is_logged }}
{{^ is_logged }}
Hey there!
{{/ is_logged }}
EOS;

echo $m->render($tpl, [
  'greeting' => 'Hello',
]);;
```

**Comment by Pok4** [comment]
Awww :) Super! Thank you! I will test it in late hours and if i have problem, i will write :)
