### ISSUE TITLE
Double curly brackets removed

### ISSUE THREAD

**Issue by csandanov** [bobthecow/mustache.php#395]
Hi, we've been using mustache on our project for years to replace `{{tokens}}` with values and today I've caught a bug (or maybe behaviour by design) where I had a password that was generated with double open curly brackets and brackets were just removed, e.g. `{{password` turns into `password`. Is this how it supposed to work? Is it possible to change that behaviour? 

I'm using v2.12, didn't find anything related in the changelog

Reproduction link (v2.14.1): https://phpsandbox.io/n/dark-sun-3r7k-fhavg

go and js versions of mustache both return errors when there's unclosed tag which I think is better than just silently removing it

**Comment by bobthecow** [comment]
Sorry, somehow I missed this issue! It looks like your sandbox link isn't working now. Can you put a repro case in the issue so I can take a look?

**Comment by csandanov** [comment]
🤔 the sandbox works fine for me, just needed a couple of reload of the built-in browser https://phpsandbox.io/n/dark-sun-3r7k-fhavg

**Comment by bobthecow** [comment]
Weird. It wasn't working at all (I tried loading it at least a dozen times).

**Comment by bobthecow** [comment]
Okay, thanks for reporting this! Mustache.php will now throw exceptions for unclosed tags, rather than rendering the tag name as text :) 

The fix will be available in the next release.
