### ISSUE TITLE
Functions resolving before properties

### ISSUE THREAD

**Issue by ahwelp** [bobthecow/mustache.php#397]
Hey all!

I faced a strange behavior on mustache. 
If a object is provided as a context, but this object has a key and a function with the same name, the function takes precedence. 

For example:
```
class Chris {
    public $name  = "Chris";
    public $value = 10000;

    public function value() {
        return 6000;
    }
}

$m = new Mustache_Engine(array("entity_flags" => ENT_QUOTES));
$chris = new Chris;
echo $m->render("Hello {{name}} You have just won {{value}} dollars!", $chris);
```

The result would be:
```
Hello Chris  You have just won 6000 dollars!
```

Is this the correct behavior for mustache?

**Comment by bobthecow** [comment]
This is the correct behavior! See https://github.com/bobthecow/mustache.php/wiki/Variable-Resolution for the exact precedence.
