### ISSUE TITLE
The version notation in the Zip file was not up-to-date. In the latest release v2.14.1 tag.

### ISSUE THREAD

**Issue by yama-dev** [bobthecow/mustache.php#403]
Hello, thanks for this useful software !

Within the latest release of the v2.14.1 tag, the
https://github.com/bobthecow/mustache.php/releases/tag/v2.14.1
The versioning of the Zip file was not up to date.

Zip file.
https://github.com/bobthecow/mustache.php/archive/refs/tags/v2.14.1.zip
https://github.com/bobthecow/mustache.php/blob/v2.14.1/src/Mustache/Engine.php#L26

**Comment by bobthecow** [comment]
oh, thanks for the heads up!
