### ISSUE TITLE
Option to minify html output

### ISSUE THREAD

**Issue by Pok4** [bobthecow/mustache.php#411]
Can you add a option to minify html ? 
Or can you tell me a variant for this ?
Thank you in advance!

**Comment by bobthecow** [comment]
Minifying HTML is an entirely separate concern. You should probably pass the output of mustache to a library made for that :)

**Comment by Pok4** [comment]
Give me example please. Here (https://www.geeksforgeeks.org/how-to-minify-html-code-of-php-page/amp/) is simple php code for minify. If you have time, please give me example..

**Comment by bobthecow** [comment]
I have no experience with HTML minification in PHP, but I'd find a library (maybe [HtmlMin](https://github.com/voku/HtmlMin)? ¯\\\_(ツ)\_/¯) and look at its docs to see how to use it. I bet it looks something like this:

```php
$m = new Mustache_Engine(...);
$html = $m->render(...);
$htmlMin = new HtmlMin();
echo $htmlMin->minify($html);
```

**Comment by Pok4** [comment]
Thank you, it works!
