### ISSUE TITLE
internationalization with Mustache and sprintf

### ISSUE THREAD

**Issue by gingerlime** [bobthecow/mustache.php#69]
Sorry if this might seem as a double-post from stack-overflow (http://stackoverflow.com/questions/8695970/mustache-i18n-with-parameters/) but I'm really struggling with this and would appreciate any pointers.

I've read about higher order sections, and even though lambdas generally confuse me, I think I managed to implement something basic to do i18n of simple text with Mustache (I can copy&paste the code, but it's already on SO). 

However, I'd really like to find a good (or reasonable) replacement for things like `sprintf(__('translated %s with parameters'), $string)`

Can anybody suggest something? Did I miss something obvious (or not so obvious)?

**Comment by Tklaversma** [comment]
@bobthecow  Hi Bob, I was wondering if you could help me out. As you described [here](https://github.com/bobthecow/mustache.php/issues/69#issuecomment-32428862) (two comments above), in order for Poedit to automatically recognize strings that needs translation, I need to create a walker of some sort. But how will this walker actually help Poedit to see these strings when I press 'Update catalog' in Poedit?

I think that's what @davekiss ment. Maybe you already answered the question, but I still do not get it. If you could explain again :)?
